namespace barcodescanner.Forms
{
    partial class AddInventory
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(AddInventory));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            this.bunifuLabel6 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel5 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel4 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel3 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel2 = new Bunifu.UI.WinForms.BunifuLabel();
            this.dpCategory = new Bunifu.UI.WinForms.BunifuDropdown();
            this.txtMindeus = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel1 = new Bunifu.UI.WinForms.BunifuLabel();
            this.dpSupplier = new Bunifu.UI.WinForms.BunifuDropdown();
            this.bunifuLabel7 = new Bunifu.UI.WinForms.BunifuLabel();
            this.btnAddImage = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.pcbItem = new Bunifu.UI.WinForms.BunifuPictureBox();
            this.picQR = new System.Windows.Forms.PictureBox();
            this.bunifuButton1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bttnSave = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.txtUP = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtQuan = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtPN = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuElipse1 = new Bunifu.Framework.UI.BunifuElipse(this.components);
            this.btnGenerate = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuPanel1 = new Bunifu.UI.WinForms.BunifuPanel();
            this.btnPrint = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.txtQRCode = new Bunifu.UI.WinForms.BunifuTextBox();
            ((System.ComponentModel.ISupportInitialize)(this.pcbItem)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.picQR)).BeginInit();
            this.bunifuPanel1.SuspendLayout();
            this.SuspendLayout();
            // 
            // bunifuLabel6
            // 
            this.bunifuLabel6.AllowParentOverrides = false;
            this.bunifuLabel6.AutoEllipsis = false;
            this.bunifuLabel6.CursorType = null;
            this.bunifuLabel6.Font = new System.Drawing.Font("Segoe UI Semibold", 14.25F, System.Drawing.FontStyle.Bold);
            this.bunifuLabel6.Location = new System.Drawing.Point(82, 446);
            this.bunifuLabel6.Name = "bunifuLabel6";
            this.bunifuLabel6.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel6.Size = new System.Drawing.Size(70, 25);
            this.bunifuLabel6.TabIndex = 40;
            this.bunifuLabel6.Text = "Supplier";
            this.bunifuLabel6.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel6.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel5
            // 
            this.bunifuLabel5.AllowParentOverrides = false;
            this.bunifuLabel5.AutoEllipsis = false;
            this.bunifuLabel5.CursorType = null;
            this.bunifuLabel5.Font = new System.Drawing.Font("Segoe UI Semibold", 14.25F, System.Drawing.FontStyle.Bold);
            this.bunifuLabel5.Location = new System.Drawing.Point(82, 390);
            this.bunifuLabel5.Name = "bunifuLabel5";
            this.bunifuLabel5.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel5.Size = new System.Drawing.Size(83, 25);
            this.bunifuLabel5.TabIndex = 39;
            this.bunifuLabel5.Text = "Unit Price";
            this.bunifuLabel5.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel5.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel4
            // 
            this.bunifuLabel4.AllowParentOverrides = false;
            this.bunifuLabel4.AutoEllipsis = false;
            this.bunifuLabel4.CursorType = null;
            this.bunifuLabel4.Font = new System.Drawing.Font("Segoe UI Semibold", 14.25F, System.Drawing.FontStyle.Bold);
            this.bunifuLabel4.Location = new System.Drawing.Point(86, 330);
            this.bunifuLabel4.Name = "bunifuLabel4";
            this.bunifuLabel4.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel4.Size = new System.Drawing.Size(75, 25);
            this.bunifuLabel4.TabIndex = 38;
            this.bunifuLabel4.Text = "Quantity";
            this.bunifuLabel4.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel4.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel3
            // 
            this.bunifuLabel3.AllowParentOverrides = false;
            this.bunifuLabel3.AutoEllipsis = false;
            this.bunifuLabel3.CursorType = null;
            this.bunifuLabel3.Font = new System.Drawing.Font("Segoe UI Semibold", 14.25F, System.Drawing.FontStyle.Bold);
            this.bunifuLabel3.Location = new System.Drawing.Point(86, 265);
            this.bunifuLabel3.Name = "bunifuLabel3";
            this.bunifuLabel3.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel3.Size = new System.Drawing.Size(78, 25);
            this.bunifuLabel3.TabIndex = 37;
            this.bunifuLabel3.Text = "Category";
            this.bunifuLabel3.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel3.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel2
            // 
            this.bunifuLabel2.AllowParentOverrides = false;
            this.bunifuLabel2.AutoEllipsis = false;
            this.bunifuLabel2.CursorType = null;
            this.bunifuLabel2.Font = new System.Drawing.Font("Segoe UI Semibold", 14.25F, System.Drawing.FontStyle.Bold);
            this.bunifuLabel2.Location = new System.Drawing.Point(40, 201);
            this.bunifuLabel2.Name = "bunifuLabel2";
            this.bunifuLabel2.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel2.Size = new System.Drawing.Size(124, 25);
            this.bunifuLabel2.TabIndex = 36;
            this.bunifuLabel2.Text = "Product Name";
            this.bunifuLabel2.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel2.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // dpCategory
            // 
            this.dpCategory.BackColor = System.Drawing.Color.Transparent;
            this.dpCategory.BackgroundColor = System.Drawing.Color.White;
            this.dpCategory.BorderColor = System.Drawing.Color.Silver;
            this.dpCategory.BorderRadius = 1;
            this.dpCategory.Color = System.Drawing.Color.Silver;
            this.dpCategory.Direction = Bunifu.UI.WinForms.BunifuDropdown.Directions.Down;
            this.dpCategory.DisabledBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.dpCategory.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.dpCategory.DisabledColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.dpCategory.DisabledForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            this.dpCategory.DisabledIndicatorColor = System.Drawing.Color.DarkGray;
            this.dpCategory.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
            this.dpCategory.DropdownBorderThickness = Bunifu.UI.WinForms.BunifuDropdown.BorderThickness.Thin;
            this.dpCategory.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.dpCategory.DropDownTextAlign = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.dpCategory.FillDropDown = true;
            this.dpCategory.FillIndicator = false;
            this.dpCategory.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.dpCategory.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.dpCategory.ForeColor = System.Drawing.Color.Black;
            this.dpCategory.FormattingEnabled = true;
            this.dpCategory.Icon = null;
            this.dpCategory.IndicatorAlignment = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.dpCategory.IndicatorColor = System.Drawing.Color.Gray;
            this.dpCategory.IndicatorLocation = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.dpCategory.ItemBackColor = System.Drawing.Color.White;
            this.dpCategory.ItemBorderColor = System.Drawing.Color.White;
            this.dpCategory.ItemForeColor = System.Drawing.Color.Black;
            this.dpCategory.ItemHeight = 26;
            this.dpCategory.ItemHighLightColor = System.Drawing.Color.DodgerBlue;
            this.dpCategory.ItemHighLightForeColor = System.Drawing.Color.White;
            this.dpCategory.ItemTopMargin = 3;
            this.dpCategory.Location = new System.Drawing.Point(183, 258);
            this.dpCategory.Name = "dpCategory";
            this.dpCategory.Size = new System.Drawing.Size(249, 32);
            this.dpCategory.TabIndex = 47;
            this.dpCategory.Text = null;
            this.dpCategory.TextAlignment = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.dpCategory.TextLeftMargin = 5;
            // 
            // txtMindeus
            // 
            this.txtMindeus.AllowParentOverrides = false;
            this.txtMindeus.AutoEllipsis = false;
            this.txtMindeus.Cursor = System.Windows.Forms.Cursors.Default;
            this.txtMindeus.CursorType = System.Windows.Forms.Cursors.Default;
            this.txtMindeus.Font = new System.Drawing.Font("Gadugi", 26.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtMindeus.ForeColor = System.Drawing.Color.DarkBlue;
            this.txtMindeus.Location = new System.Drawing.Point(70, 42);
            this.txtMindeus.Name = "txtMindeus";
            this.txtMindeus.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.txtMindeus.Size = new System.Drawing.Size(11, 41);
            this.txtMindeus.TabIndex = 49;
            this.txtMindeus.Text = "|";
            this.txtMindeus.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.txtMindeus.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            this.txtMindeus.Click += new System.EventHandler(this.txtMindeus_Click);
            // 
            // bunifuLabel1
            // 
            this.bunifuLabel1.AllowParentOverrides = false;
            this.bunifuLabel1.AutoEllipsis = false;
            this.bunifuLabel1.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.Font = new System.Drawing.Font("Gadugi", 26.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel1.ForeColor = System.Drawing.Color.Black;
            this.bunifuLabel1.Location = new System.Drawing.Point(87, 46);
            this.bunifuLabel1.Name = "bunifuLabel1";
            this.bunifuLabel1.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel1.Size = new System.Drawing.Size(322, 41);
            this.bunifuLabel1.TabIndex = 50;
            this.bunifuLabel1.Text = "Add Item / Product";
            this.bunifuLabel1.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel1.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // dpSupplier
            // 
            this.dpSupplier.BackColor = System.Drawing.Color.Transparent;
            this.dpSupplier.BackgroundColor = System.Drawing.Color.White;
            this.dpSupplier.BorderColor = System.Drawing.Color.Silver;
            this.dpSupplier.BorderRadius = 1;
            this.dpSupplier.Color = System.Drawing.Color.Silver;
            this.dpSupplier.Direction = Bunifu.UI.WinForms.BunifuDropdown.Directions.Down;
            this.dpSupplier.DisabledBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.dpSupplier.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.dpSupplier.DisabledColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.dpSupplier.DisabledForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            this.dpSupplier.DisabledIndicatorColor = System.Drawing.Color.DarkGray;
            this.dpSupplier.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
            this.dpSupplier.DropdownBorderThickness = Bunifu.UI.WinForms.BunifuDropdown.BorderThickness.Thin;
            this.dpSupplier.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.dpSupplier.DropDownTextAlign = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.dpSupplier.FillDropDown = true;
            this.dpSupplier.FillIndicator = false;
            this.dpSupplier.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.dpSupplier.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.dpSupplier.ForeColor = System.Drawing.Color.Black;
            this.dpSupplier.FormattingEnabled = true;
            this.dpSupplier.Icon = null;
            this.dpSupplier.IndicatorAlignment = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.dpSupplier.IndicatorColor = System.Drawing.Color.Gray;
            this.dpSupplier.IndicatorLocation = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.dpSupplier.ItemBackColor = System.Drawing.Color.White;
            this.dpSupplier.ItemBorderColor = System.Drawing.Color.White;
            this.dpSupplier.ItemForeColor = System.Drawing.Color.Black;
            this.dpSupplier.ItemHeight = 26;
            this.dpSupplier.ItemHighLightColor = System.Drawing.Color.DodgerBlue;
            this.dpSupplier.ItemHighLightForeColor = System.Drawing.Color.White;
            this.dpSupplier.ItemTopMargin = 3;
            this.dpSupplier.Location = new System.Drawing.Point(183, 439);
            this.dpSupplier.Name = "dpSupplier";
            this.dpSupplier.Size = new System.Drawing.Size(249, 32);
            this.dpSupplier.TabIndex = 51;
            this.dpSupplier.Text = null;
            this.dpSupplier.TextAlignment = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.dpSupplier.TextLeftMargin = 5;
            // 
            // bunifuLabel7
            // 
            this.bunifuLabel7.AllowParentOverrides = false;
            this.bunifuLabel7.AutoEllipsis = false;
            this.bunifuLabel7.CursorType = null;
            this.bunifuLabel7.Font = new System.Drawing.Font("Segoe UI Semibold", 14.25F, System.Drawing.FontStyle.Bold);
            this.bunifuLabel7.Location = new System.Drawing.Point(70, 140);
            this.bunifuLabel7.Name = "bunifuLabel7";
            this.bunifuLabel7.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel7.Size = new System.Drawing.Size(93, 25);
            this.bunifuLabel7.TabIndex = 52;
            this.bunifuLabel7.Text = "Product Qr";
            this.bunifuLabel7.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel7.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // btnAddImage
            // 
            this.btnAddImage.AllowAnimations = true;
            this.btnAddImage.AllowMouseEffects = true;
            this.btnAddImage.AllowToggling = false;
            this.btnAddImage.AnimationSpeed = 200;
            this.btnAddImage.AutoGenerateColors = false;
            this.btnAddImage.AutoRoundBorders = false;
            this.btnAddImage.AutoSizeLeftIcon = true;
            this.btnAddImage.AutoSizeRightIcon = true;
            this.btnAddImage.BackColor = System.Drawing.Color.Transparent;
            this.btnAddImage.BackColor1 = System.Drawing.SystemColors.Control;
            this.btnAddImage.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnAddImage.BackgroundImage")));
            this.btnAddImage.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnAddImage.ButtonText = "Insert";
            this.btnAddImage.ButtonTextMarginLeft = 0;
            this.btnAddImage.ColorContrastOnClick = 45;
            this.btnAddImage.ColorContrastOnHover = 45;
            this.btnAddImage.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.btnAddImage.CustomizableEdges = borderEdges1;
            this.btnAddImage.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnAddImage.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnAddImage.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnAddImage.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnAddImage.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnAddImage.Font = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Bold);
            this.btnAddImage.ForeColor = System.Drawing.Color.Black;
            this.btnAddImage.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnAddImage.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnAddImage.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnAddImage.IconMarginLeft = 11;
            this.btnAddImage.IconPadding = 10;
            this.btnAddImage.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnAddImage.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnAddImage.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnAddImage.IconSize = 25;
            this.btnAddImage.IdleBorderColor = System.Drawing.Color.Black;
            this.btnAddImage.IdleBorderRadius = 18;
            this.btnAddImage.IdleBorderThickness = 1;
            this.btnAddImage.IdleFillColor = System.Drawing.SystemColors.Control;
            this.btnAddImage.IdleIconLeftImage = null;
            this.btnAddImage.IdleIconRightImage = null;
            this.btnAddImage.IndicateFocus = false;
            this.btnAddImage.Location = new System.Drawing.Point(82, 260);
            this.btnAddImage.Name = "btnAddImage";
            this.btnAddImage.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnAddImage.OnDisabledState.BorderRadius = 18;
            this.btnAddImage.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnAddImage.OnDisabledState.BorderThickness = 1;
            this.btnAddImage.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnAddImage.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnAddImage.OnDisabledState.IconLeftImage = null;
            this.btnAddImage.OnDisabledState.IconRightImage = null;
            this.btnAddImage.onHoverState.BorderColor = System.Drawing.SystemColors.Control;
            this.btnAddImage.onHoverState.BorderRadius = 18;
            this.btnAddImage.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnAddImage.onHoverState.BorderThickness = 1;
            this.btnAddImage.onHoverState.FillColor = System.Drawing.Color.DarkBlue;
            this.btnAddImage.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnAddImage.onHoverState.IconLeftImage = null;
            this.btnAddImage.onHoverState.IconRightImage = null;
            this.btnAddImage.OnIdleState.BorderColor = System.Drawing.Color.Black;
            this.btnAddImage.OnIdleState.BorderRadius = 18;
            this.btnAddImage.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnAddImage.OnIdleState.BorderThickness = 1;
            this.btnAddImage.OnIdleState.FillColor = System.Drawing.SystemColors.Control;
            this.btnAddImage.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.btnAddImage.OnIdleState.IconLeftImage = null;
            this.btnAddImage.OnIdleState.IconRightImage = null;
            this.btnAddImage.OnPressedState.BorderColor = System.Drawing.SystemColors.Control;
            this.btnAddImage.OnPressedState.BorderRadius = 18;
            this.btnAddImage.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnAddImage.OnPressedState.BorderThickness = 1;
            this.btnAddImage.OnPressedState.FillColor = System.Drawing.Color.DarkBlue;
            this.btnAddImage.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnAddImage.OnPressedState.IconLeftImage = null;
            this.btnAddImage.OnPressedState.IconRightImage = null;
            this.btnAddImage.Size = new System.Drawing.Size(104, 28);
            this.btnAddImage.TabIndex = 56;
            this.btnAddImage.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnAddImage.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnAddImage.TextMarginLeft = 0;
            this.btnAddImage.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnAddImage.UseDefaultRadiusAndThickness = true;
            this.btnAddImage.Click += new System.EventHandler(this.btnAddImage_Click);
            // 
            // pcbItem
            // 
            this.pcbItem.AllowFocused = false;
            this.pcbItem.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.pcbItem.AutoSizeHeight = true;
            this.pcbItem.BorderRadius = 0;
            this.pcbItem.Image = ((System.Drawing.Image)(resources.GetObject("pcbItem.Image")));
            this.pcbItem.IsCircle = true;
            this.pcbItem.Location = new System.Drawing.Point(28, 39);
            this.pcbItem.Name = "pcbItem";
            this.pcbItem.Size = new System.Drawing.Size(215, 215);
            this.pcbItem.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.pcbItem.TabIndex = 55;
            this.pcbItem.TabStop = false;
            this.pcbItem.Type = Bunifu.UI.WinForms.BunifuPictureBox.Types.Square;
            // 
            // picQR
            // 
            this.picQR.Location = new System.Drawing.Point(267, 39);
            this.picQR.Name = "picQR";
            this.picQR.Size = new System.Drawing.Size(226, 215);
            this.picQR.SizeMode = System.Windows.Forms.PictureBoxSizeMode.StretchImage;
            this.picQR.TabIndex = 54;
            this.picQR.TabStop = false;
            // 
            // bunifuButton1
            // 
            this.bunifuButton1.AllowAnimations = true;
            this.bunifuButton1.AllowMouseEffects = true;
            this.bunifuButton1.AllowToggling = false;
            this.bunifuButton1.AnimationSpeed = 200;
            this.bunifuButton1.AutoGenerateColors = false;
            this.bunifuButton1.AutoRoundBorders = false;
            this.bunifuButton1.AutoSizeLeftIcon = true;
            this.bunifuButton1.AutoSizeRightIcon = true;
            this.bunifuButton1.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButton1.BackColor1 = System.Drawing.SystemColors.Control;
            this.bunifuButton1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton1.BackgroundImage")));
            this.bunifuButton1.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.ButtonText = "Cancel";
            this.bunifuButton1.ButtonTextMarginLeft = 0;
            this.bunifuButton1.ColorContrastOnClick = 45;
            this.bunifuButton1.ColorContrastOnHover = 45;
            this.bunifuButton1.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.bunifuButton1.CustomizableEdges = borderEdges2;
            this.bunifuButton1.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButton1.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton1.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton1.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton1.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.bunifuButton1.Font = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Bold);
            this.bunifuButton1.ForeColor = System.Drawing.Color.Black;
            this.bunifuButton1.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButton1.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton1.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bunifuButton1.IconMarginLeft = 11;
            this.bunifuButton1.IconPadding = 10;
            this.bunifuButton1.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButton1.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton1.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bunifuButton1.IconSize = 25;
            this.bunifuButton1.IdleBorderColor = System.Drawing.Color.Black;
            this.bunifuButton1.IdleBorderRadius = 18;
            this.bunifuButton1.IdleBorderThickness = 1;
            this.bunifuButton1.IdleFillColor = System.Drawing.SystemColors.Control;
            this.bunifuButton1.IdleIconLeftImage = null;
            this.bunifuButton1.IdleIconRightImage = null;
            this.bunifuButton1.IndicateFocus = false;
            this.bunifuButton1.Location = new System.Drawing.Point(807, 479);
            this.bunifuButton1.Name = "bunifuButton1";
            this.bunifuButton1.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton1.OnDisabledState.BorderRadius = 18;
            this.bunifuButton1.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.OnDisabledState.BorderThickness = 1;
            this.bunifuButton1.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton1.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton1.OnDisabledState.IconLeftImage = null;
            this.bunifuButton1.OnDisabledState.IconRightImage = null;
            this.bunifuButton1.onHoverState.BorderColor = System.Drawing.SystemColors.Control;
            this.bunifuButton1.onHoverState.BorderRadius = 18;
            this.bunifuButton1.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.onHoverState.BorderThickness = 1;
            this.bunifuButton1.onHoverState.FillColor = System.Drawing.Color.Red;
            this.bunifuButton1.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton1.onHoverState.IconLeftImage = null;
            this.bunifuButton1.onHoverState.IconRightImage = null;
            this.bunifuButton1.OnIdleState.BorderColor = System.Drawing.Color.Black;
            this.bunifuButton1.OnIdleState.BorderRadius = 18;
            this.bunifuButton1.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.OnIdleState.BorderThickness = 1;
            this.bunifuButton1.OnIdleState.FillColor = System.Drawing.SystemColors.Control;
            this.bunifuButton1.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.bunifuButton1.OnIdleState.IconLeftImage = null;
            this.bunifuButton1.OnIdleState.IconRightImage = null;
            this.bunifuButton1.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton1.OnPressedState.BorderRadius = 18;
            this.bunifuButton1.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.OnPressedState.BorderThickness = 1;
            this.bunifuButton1.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton1.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton1.OnPressedState.IconLeftImage = null;
            this.bunifuButton1.OnPressedState.IconRightImage = null;
            this.bunifuButton1.Size = new System.Drawing.Size(121, 39);
            this.bunifuButton1.TabIndex = 48;
            this.bunifuButton1.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuButton1.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButton1.TextMarginLeft = 0;
            this.bunifuButton1.TextPadding = new System.Windows.Forms.Padding(0);
            this.bunifuButton1.UseDefaultRadiusAndThickness = true;
            this.bunifuButton1.Click += new System.EventHandler(this.bunifuButton1_Click);
            // 
            // bttnSave
            // 
            this.bttnSave.AllowAnimations = true;
            this.bttnSave.AllowMouseEffects = true;
            this.bttnSave.AllowToggling = false;
            this.bttnSave.AnimationSpeed = 200;
            this.bttnSave.AutoGenerateColors = false;
            this.bttnSave.AutoRoundBorders = false;
            this.bttnSave.AutoSizeLeftIcon = true;
            this.bttnSave.AutoSizeRightIcon = true;
            this.bttnSave.BackColor = System.Drawing.Color.Transparent;
            this.bttnSave.BackColor1 = System.Drawing.SystemColors.Control;
            this.bttnSave.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bttnSave.BackgroundImage")));
            this.bttnSave.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bttnSave.ButtonText = "Save";
            this.bttnSave.ButtonTextMarginLeft = 0;
            this.bttnSave.ColorContrastOnClick = 45;
            this.bttnSave.ColorContrastOnHover = 45;
            this.bttnSave.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.bttnSave.CustomizableEdges = borderEdges3;
            this.bttnSave.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bttnSave.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bttnSave.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bttnSave.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bttnSave.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.bttnSave.Font = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Bold);
            this.bttnSave.ForeColor = System.Drawing.Color.Black;
            this.bttnSave.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bttnSave.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bttnSave.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bttnSave.IconMarginLeft = 11;
            this.bttnSave.IconPadding = 10;
            this.bttnSave.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bttnSave.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bttnSave.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bttnSave.IconSize = 25;
            this.bttnSave.IdleBorderColor = System.Drawing.Color.Black;
            this.bttnSave.IdleBorderRadius = 18;
            this.bttnSave.IdleBorderThickness = 1;
            this.bttnSave.IdleFillColor = System.Drawing.SystemColors.Control;
            this.bttnSave.IdleIconLeftImage = null;
            this.bttnSave.IdleIconRightImage = null;
            this.bttnSave.IndicateFocus = false;
            this.bttnSave.Location = new System.Drawing.Point(677, 479);
            this.bttnSave.Name = "bttnSave";
            this.bttnSave.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bttnSave.OnDisabledState.BorderRadius = 18;
            this.bttnSave.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bttnSave.OnDisabledState.BorderThickness = 1;
            this.bttnSave.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bttnSave.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bttnSave.OnDisabledState.IconLeftImage = null;
            this.bttnSave.OnDisabledState.IconRightImage = null;
            this.bttnSave.onHoverState.BorderColor = System.Drawing.SystemColors.Control;
            this.bttnSave.onHoverState.BorderRadius = 18;
            this.bttnSave.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bttnSave.onHoverState.BorderThickness = 1;
            this.bttnSave.onHoverState.FillColor = System.Drawing.Color.DarkBlue;
            this.bttnSave.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bttnSave.onHoverState.IconLeftImage = null;
            this.bttnSave.onHoverState.IconRightImage = null;
            this.bttnSave.OnIdleState.BorderColor = System.Drawing.Color.Black;
            this.bttnSave.OnIdleState.BorderRadius = 18;
            this.bttnSave.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bttnSave.OnIdleState.BorderThickness = 1;
            this.bttnSave.OnIdleState.FillColor = System.Drawing.SystemColors.Control;
            this.bttnSave.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.bttnSave.OnIdleState.IconLeftImage = null;
            this.bttnSave.OnIdleState.IconRightImage = null;
            this.bttnSave.OnPressedState.BorderColor = System.Drawing.SystemColors.Control;
            this.bttnSave.OnPressedState.BorderRadius = 18;
            this.bttnSave.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bttnSave.OnPressedState.BorderThickness = 1;
            this.bttnSave.OnPressedState.FillColor = System.Drawing.Color.DarkBlue;
            this.bttnSave.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bttnSave.OnPressedState.IconLeftImage = null;
            this.bttnSave.OnPressedState.IconRightImage = null;
            this.bttnSave.Size = new System.Drawing.Size(121, 39);
            this.bttnSave.TabIndex = 43;
            this.bttnSave.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bttnSave.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bttnSave.TextMarginLeft = 0;
            this.bttnSave.TextPadding = new System.Windows.Forms.Padding(0);
            this.bttnSave.UseDefaultRadiusAndThickness = true;
            this.bttnSave.Click += new System.EventHandler(this.bttnSave_Click);
            // 
            // txtUP
            // 
            this.txtUP.AcceptsReturn = false;
            this.txtUP.AcceptsTab = false;
            this.txtUP.AnimationSpeed = 200;
            this.txtUP.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtUP.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtUP.BackColor = System.Drawing.Color.Transparent;
            this.txtUP.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtUP.BackgroundImage")));
            this.txtUP.BorderColorActive = System.Drawing.Color.DarkBlue;
            this.txtUP.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtUP.BorderColorHover = System.Drawing.Color.DarkBlue;
            this.txtUP.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtUP.BorderRadius = 15;
            this.txtUP.BorderThickness = 1;
            this.txtUP.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtUP.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtUP.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtUP.DefaultText = "";
            this.txtUP.FillColor = System.Drawing.Color.White;
            this.txtUP.HideSelection = true;
            this.txtUP.IconLeft = null;
            this.txtUP.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtUP.IconPadding = 10;
            this.txtUP.IconRight = null;
            this.txtUP.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtUP.Lines = new string[0];
            this.txtUP.Location = new System.Drawing.Point(183, 379);
            this.txtUP.MaxLength = 32767;
            this.txtUP.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtUP.Modified = false;
            this.txtUP.Multiline = false;
            this.txtUP.Name = "txtUP";
            stateProperties1.BorderColor = System.Drawing.Color.DarkBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtUP.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtUP.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.DarkBlue;
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtUP.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtUP.OnIdleState = stateProperties4;
            this.txtUP.Padding = new System.Windows.Forms.Padding(3);
            this.txtUP.PasswordChar = '\0';
            this.txtUP.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtUP.PlaceholderText = "Product Price";
            this.txtUP.ReadOnly = false;
            this.txtUP.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtUP.SelectedText = "";
            this.txtUP.SelectionLength = 0;
            this.txtUP.SelectionStart = 0;
            this.txtUP.ShortcutsEnabled = true;
            this.txtUP.Size = new System.Drawing.Size(249, 36);
            this.txtUP.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtUP.TabIndex = 34;
            this.txtUP.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtUP.TextMarginBottom = 0;
            this.txtUP.TextMarginLeft = 3;
            this.txtUP.TextMarginTop = 0;
            this.txtUP.TextPlaceholder = "Product Price";
            this.txtUP.UseSystemPasswordChar = false;
            this.txtUP.WordWrap = true;
            // 
            // txtQuan
            // 
            this.txtQuan.AcceptsReturn = false;
            this.txtQuan.AcceptsTab = false;
            this.txtQuan.AnimationSpeed = 200;
            this.txtQuan.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtQuan.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtQuan.BackColor = System.Drawing.Color.Transparent;
            this.txtQuan.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtQuan.BackgroundImage")));
            this.txtQuan.BorderColorActive = System.Drawing.Color.DarkBlue;
            this.txtQuan.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtQuan.BorderColorHover = System.Drawing.Color.DarkBlue;
            this.txtQuan.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtQuan.BorderRadius = 15;
            this.txtQuan.BorderThickness = 1;
            this.txtQuan.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtQuan.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtQuan.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtQuan.DefaultText = "";
            this.txtQuan.FillColor = System.Drawing.Color.White;
            this.txtQuan.HideSelection = true;
            this.txtQuan.IconLeft = null;
            this.txtQuan.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtQuan.IconPadding = 10;
            this.txtQuan.IconRight = null;
            this.txtQuan.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtQuan.Lines = new string[0];
            this.txtQuan.Location = new System.Drawing.Point(183, 319);
            this.txtQuan.MaxLength = 32767;
            this.txtQuan.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtQuan.Modified = false;
            this.txtQuan.Multiline = false;
            this.txtQuan.Name = "txtQuan";
            stateProperties5.BorderColor = System.Drawing.Color.DarkBlue;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtQuan.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtQuan.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.DarkBlue;
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtQuan.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Silver;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Empty;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtQuan.OnIdleState = stateProperties8;
            this.txtQuan.Padding = new System.Windows.Forms.Padding(3);
            this.txtQuan.PasswordChar = '\0';
            this.txtQuan.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtQuan.PlaceholderText = "Product Quantity";
            this.txtQuan.ReadOnly = false;
            this.txtQuan.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtQuan.SelectedText = "";
            this.txtQuan.SelectionLength = 0;
            this.txtQuan.SelectionStart = 0;
            this.txtQuan.ShortcutsEnabled = true;
            this.txtQuan.Size = new System.Drawing.Size(249, 36);
            this.txtQuan.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtQuan.TabIndex = 33;
            this.txtQuan.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtQuan.TextMarginBottom = 0;
            this.txtQuan.TextMarginLeft = 3;
            this.txtQuan.TextMarginTop = 0;
            this.txtQuan.TextPlaceholder = "Product Quantity";
            this.txtQuan.UseSystemPasswordChar = false;
            this.txtQuan.WordWrap = true;
            // 
            // txtPN
            // 
            this.txtPN.AcceptsReturn = false;
            this.txtPN.AcceptsTab = false;
            this.txtPN.AnimationSpeed = 200;
            this.txtPN.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtPN.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtPN.BackColor = System.Drawing.Color.Transparent;
            this.txtPN.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtPN.BackgroundImage")));
            this.txtPN.BorderColorActive = System.Drawing.Color.DarkBlue;
            this.txtPN.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtPN.BorderColorHover = System.Drawing.Color.DarkBlue;
            this.txtPN.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtPN.BorderRadius = 15;
            this.txtPN.BorderThickness = 1;
            this.txtPN.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtPN.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtPN.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtPN.DefaultText = "";
            this.txtPN.FillColor = System.Drawing.Color.White;
            this.txtPN.HideSelection = true;
            this.txtPN.IconLeft = null;
            this.txtPN.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtPN.IconPadding = 10;
            this.txtPN.IconRight = null;
            this.txtPN.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtPN.Lines = new string[0];
            this.txtPN.Location = new System.Drawing.Point(183, 194);
            this.txtPN.MaxLength = 32767;
            this.txtPN.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtPN.Modified = false;
            this.txtPN.Multiline = false;
            this.txtPN.Name = "txtPN";
            stateProperties9.BorderColor = System.Drawing.Color.DarkBlue;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtPN.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtPN.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.DarkBlue;
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtPN.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Silver;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Empty;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtPN.OnIdleState = stateProperties12;
            this.txtPN.Padding = new System.Windows.Forms.Padding(3);
            this.txtPN.PasswordChar = '\0';
            this.txtPN.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtPN.PlaceholderText = "Product Name";
            this.txtPN.ReadOnly = false;
            this.txtPN.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtPN.SelectedText = "";
            this.txtPN.SelectionLength = 0;
            this.txtPN.SelectionStart = 0;
            this.txtPN.ShortcutsEnabled = true;
            this.txtPN.Size = new System.Drawing.Size(249, 36);
            this.txtPN.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtPN.TabIndex = 32;
            this.txtPN.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtPN.TextMarginBottom = 0;
            this.txtPN.TextMarginLeft = 3;
            this.txtPN.TextMarginTop = 0;
            this.txtPN.TextPlaceholder = "Product Name";
            this.txtPN.UseSystemPasswordChar = false;
            this.txtPN.WordWrap = true;
            // 
            // bunifuElipse1
            // 
            this.bunifuElipse1.ElipseRadius = 50;
            this.bunifuElipse1.TargetControl = this;
            // 
            // btnGenerate
            // 
            this.btnGenerate.AllowAnimations = true;
            this.btnGenerate.AllowMouseEffects = true;
            this.btnGenerate.AllowToggling = false;
            this.btnGenerate.AnimationSpeed = 200;
            this.btnGenerate.AutoGenerateColors = false;
            this.btnGenerate.AutoRoundBorders = false;
            this.btnGenerate.AutoSizeLeftIcon = true;
            this.btnGenerate.AutoSizeRightIcon = true;
            this.btnGenerate.BackColor = System.Drawing.Color.Transparent;
            this.btnGenerate.BackColor1 = System.Drawing.SystemColors.Control;
            this.btnGenerate.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnGenerate.BackgroundImage")));
            this.btnGenerate.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnGenerate.ButtonText = "Generate QR";
            this.btnGenerate.ButtonTextMarginLeft = 0;
            this.btnGenerate.ColorContrastOnClick = 45;
            this.btnGenerate.ColorContrastOnHover = 45;
            this.btnGenerate.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.btnGenerate.CustomizableEdges = borderEdges5;
            this.btnGenerate.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnGenerate.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnGenerate.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnGenerate.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnGenerate.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnGenerate.Font = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Bold);
            this.btnGenerate.ForeColor = System.Drawing.Color.Black;
            this.btnGenerate.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnGenerate.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnGenerate.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnGenerate.IconMarginLeft = 11;
            this.btnGenerate.IconPadding = 10;
            this.btnGenerate.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnGenerate.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnGenerate.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnGenerate.IconSize = 25;
            this.btnGenerate.IdleBorderColor = System.Drawing.Color.Black;
            this.btnGenerate.IdleBorderRadius = 18;
            this.btnGenerate.IdleBorderThickness = 1;
            this.btnGenerate.IdleFillColor = System.Drawing.SystemColors.Control;
            this.btnGenerate.IdleIconLeftImage = null;
            this.btnGenerate.IdleIconRightImage = null;
            this.btnGenerate.IndicateFocus = false;
            this.btnGenerate.Location = new System.Drawing.Point(274, 260);
            this.btnGenerate.Name = "btnGenerate";
            this.btnGenerate.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnGenerate.OnDisabledState.BorderRadius = 18;
            this.btnGenerate.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnGenerate.OnDisabledState.BorderThickness = 1;
            this.btnGenerate.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnGenerate.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnGenerate.OnDisabledState.IconLeftImage = null;
            this.btnGenerate.OnDisabledState.IconRightImage = null;
            this.btnGenerate.onHoverState.BorderColor = System.Drawing.SystemColors.Control;
            this.btnGenerate.onHoverState.BorderRadius = 18;
            this.btnGenerate.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnGenerate.onHoverState.BorderThickness = 1;
            this.btnGenerate.onHoverState.FillColor = System.Drawing.Color.DarkBlue;
            this.btnGenerate.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnGenerate.onHoverState.IconLeftImage = null;
            this.btnGenerate.onHoverState.IconRightImage = null;
            this.btnGenerate.OnIdleState.BorderColor = System.Drawing.Color.Black;
            this.btnGenerate.OnIdleState.BorderRadius = 18;
            this.btnGenerate.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnGenerate.OnIdleState.BorderThickness = 1;
            this.btnGenerate.OnIdleState.FillColor = System.Drawing.SystemColors.Control;
            this.btnGenerate.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.btnGenerate.OnIdleState.IconLeftImage = null;
            this.btnGenerate.OnIdleState.IconRightImage = null;
            this.btnGenerate.OnPressedState.BorderColor = System.Drawing.SystemColors.Control;
            this.btnGenerate.OnPressedState.BorderRadius = 18;
            this.btnGenerate.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnGenerate.OnPressedState.BorderThickness = 1;
            this.btnGenerate.OnPressedState.FillColor = System.Drawing.Color.DarkBlue;
            this.btnGenerate.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnGenerate.OnPressedState.IconLeftImage = null;
            this.btnGenerate.OnPressedState.IconRightImage = null;
            this.btnGenerate.Size = new System.Drawing.Size(104, 28);
            this.btnGenerate.TabIndex = 57;
            this.btnGenerate.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnGenerate.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnGenerate.TextMarginLeft = 0;
            this.btnGenerate.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnGenerate.UseDefaultRadiusAndThickness = true;
            this.btnGenerate.Click += new System.EventHandler(this.btnGenerate_Click);
            // 
            // bunifuPanel1
            // 
            this.bunifuPanel1.BackgroundColor = System.Drawing.Color.Transparent;
            this.bunifuPanel1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuPanel1.BackgroundImage")));
            this.bunifuPanel1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuPanel1.BorderColor = System.Drawing.Color.Transparent;
            this.bunifuPanel1.BorderRadius = 3;
            this.bunifuPanel1.BorderThickness = 1;
            this.bunifuPanel1.Controls.Add(this.btnPrint);
            this.bunifuPanel1.Controls.Add(this.btnAddImage);
            this.bunifuPanel1.Controls.Add(this.btnGenerate);
            this.bunifuPanel1.Controls.Add(this.picQR);
            this.bunifuPanel1.Controls.Add(this.pcbItem);
            this.bunifuPanel1.Location = new System.Drawing.Point(446, 132);
            this.bunifuPanel1.Name = "bunifuPanel1";
            this.bunifuPanel1.ShowBorders = true;
            this.bunifuPanel1.Size = new System.Drawing.Size(509, 316);
            this.bunifuPanel1.TabIndex = 58;
            // 
            // btnPrint
            // 
            this.btnPrint.AllowAnimations = true;
            this.btnPrint.AllowMouseEffects = true;
            this.btnPrint.AllowToggling = false;
            this.btnPrint.AnimationSpeed = 200;
            this.btnPrint.AutoGenerateColors = false;
            this.btnPrint.AutoRoundBorders = false;
            this.btnPrint.AutoSizeLeftIcon = true;
            this.btnPrint.AutoSizeRightIcon = true;
            this.btnPrint.BackColor = System.Drawing.Color.Transparent;
            this.btnPrint.BackColor1 = System.Drawing.SystemColors.Control;
            this.btnPrint.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnPrint.BackgroundImage")));
            this.btnPrint.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnPrint.ButtonText = "Print QR";
            this.btnPrint.ButtonTextMarginLeft = 0;
            this.btnPrint.ColorContrastOnClick = 45;
            this.btnPrint.ColorContrastOnHover = 45;
            this.btnPrint.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.btnPrint.CustomizableEdges = borderEdges4;
            this.btnPrint.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnPrint.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnPrint.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnPrint.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnPrint.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnPrint.Font = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Bold);
            this.btnPrint.ForeColor = System.Drawing.Color.Black;
            this.btnPrint.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnPrint.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnPrint.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnPrint.IconMarginLeft = 11;
            this.btnPrint.IconPadding = 10;
            this.btnPrint.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnPrint.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnPrint.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnPrint.IconSize = 25;
            this.btnPrint.IdleBorderColor = System.Drawing.Color.Black;
            this.btnPrint.IdleBorderRadius = 18;
            this.btnPrint.IdleBorderThickness = 1;
            this.btnPrint.IdleFillColor = System.Drawing.SystemColors.Control;
            this.btnPrint.IdleIconLeftImage = null;
            this.btnPrint.IdleIconRightImage = null;
            this.btnPrint.IndicateFocus = false;
            this.btnPrint.Location = new System.Drawing.Point(389, 260);
            this.btnPrint.Name = "btnPrint";
            this.btnPrint.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnPrint.OnDisabledState.BorderRadius = 18;
            this.btnPrint.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnPrint.OnDisabledState.BorderThickness = 1;
            this.btnPrint.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnPrint.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnPrint.OnDisabledState.IconLeftImage = null;
            this.btnPrint.OnDisabledState.IconRightImage = null;
            this.btnPrint.onHoverState.BorderColor = System.Drawing.SystemColors.Control;
            this.btnPrint.onHoverState.BorderRadius = 18;
            this.btnPrint.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnPrint.onHoverState.BorderThickness = 1;
            this.btnPrint.onHoverState.FillColor = System.Drawing.Color.DarkBlue;
            this.btnPrint.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnPrint.onHoverState.IconLeftImage = null;
            this.btnPrint.onHoverState.IconRightImage = null;
            this.btnPrint.OnIdleState.BorderColor = System.Drawing.Color.Black;
            this.btnPrint.OnIdleState.BorderRadius = 18;
            this.btnPrint.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnPrint.OnIdleState.BorderThickness = 1;
            this.btnPrint.OnIdleState.FillColor = System.Drawing.SystemColors.Control;
            this.btnPrint.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.btnPrint.OnIdleState.IconLeftImage = null;
            this.btnPrint.OnIdleState.IconRightImage = null;
            this.btnPrint.OnPressedState.BorderColor = System.Drawing.SystemColors.Control;
            this.btnPrint.OnPressedState.BorderRadius = 18;
            this.btnPrint.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnPrint.OnPressedState.BorderThickness = 1;
            this.btnPrint.OnPressedState.FillColor = System.Drawing.Color.DarkBlue;
            this.btnPrint.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnPrint.OnPressedState.IconLeftImage = null;
            this.btnPrint.OnPressedState.IconRightImage = null;
            this.btnPrint.Size = new System.Drawing.Size(104, 28);
            this.btnPrint.TabIndex = 58;
            this.btnPrint.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnPrint.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnPrint.TextMarginLeft = 0;
            this.btnPrint.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnPrint.UseDefaultRadiusAndThickness = true;
            this.btnPrint.Click += new System.EventHandler(this.btnPrint_Click);
            // 
            // txtQRCode
            // 
            this.txtQRCode.AcceptsReturn = false;
            this.txtQRCode.AcceptsTab = false;
            this.txtQRCode.AnimationSpeed = 200;
            this.txtQRCode.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtQRCode.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtQRCode.BackColor = System.Drawing.Color.Transparent;
            this.txtQRCode.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtQRCode.BackgroundImage")));
            this.txtQRCode.BorderColorActive = System.Drawing.Color.DarkBlue;
            this.txtQRCode.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtQRCode.BorderColorHover = System.Drawing.Color.DarkBlue;
            this.txtQRCode.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtQRCode.BorderRadius = 15;
            this.txtQRCode.BorderThickness = 1;
            this.txtQRCode.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtQRCode.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtQRCode.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtQRCode.DefaultText = "";
            this.txtQRCode.FillColor = System.Drawing.Color.White;
            this.txtQRCode.HideSelection = true;
            this.txtQRCode.IconLeft = null;
            this.txtQRCode.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtQRCode.IconPadding = 10;
            this.txtQRCode.IconRight = null;
            this.txtQRCode.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtQRCode.Lines = new string[0];
            this.txtQRCode.Location = new System.Drawing.Point(183, 135);
            this.txtQRCode.MaxLength = 32767;
            this.txtQRCode.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtQRCode.Modified = false;
            this.txtQRCode.Multiline = false;
            this.txtQRCode.Name = "txtQRCode";
            stateProperties13.BorderColor = System.Drawing.Color.DarkBlue;
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtQRCode.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtQRCode.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.DarkBlue;
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtQRCode.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.Silver;
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.Color.Empty;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtQRCode.OnIdleState = stateProperties16;
            this.txtQRCode.Padding = new System.Windows.Forms.Padding(3);
            this.txtQRCode.PasswordChar = '\0';
            this.txtQRCode.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtQRCode.PlaceholderText = "QR Code Text";
            this.txtQRCode.ReadOnly = true;
            this.txtQRCode.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtQRCode.SelectedText = "";
            this.txtQRCode.SelectionLength = 0;
            this.txtQRCode.SelectionStart = 0;
            this.txtQRCode.ShortcutsEnabled = true;
            this.txtQRCode.Size = new System.Drawing.Size(249, 36);
            this.txtQRCode.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtQRCode.TabIndex = 59;
            this.txtQRCode.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtQRCode.TextMarginBottom = 0;
            this.txtQRCode.TextMarginLeft = 3;
            this.txtQRCode.TextMarginTop = 0;
            this.txtQRCode.TextPlaceholder = "QR Code Text";
            this.txtQRCode.UseSystemPasswordChar = false;
            this.txtQRCode.WordWrap = true;
            // 
            // AddInventory
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(967, 539);
            this.Controls.Add(this.txtQRCode);
            this.Controls.Add(this.bunifuLabel7);
            this.Controls.Add(this.dpSupplier);
            this.Controls.Add(this.bunifuLabel1);
            this.Controls.Add(this.txtMindeus);
            this.Controls.Add(this.bunifuButton1);
            this.Controls.Add(this.dpCategory);
            this.Controls.Add(this.bttnSave);
            this.Controls.Add(this.bunifuLabel6);
            this.Controls.Add(this.bunifuLabel5);
            this.Controls.Add(this.bunifuLabel4);
            this.Controls.Add(this.bunifuLabel3);
            this.Controls.Add(this.bunifuLabel2);
            this.Controls.Add(this.txtUP);
            this.Controls.Add(this.txtQuan);
            this.Controls.Add(this.txtPN);
            this.Controls.Add(this.bunifuPanel1);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Icon = ((System.Drawing.Icon)(resources.GetObject("$this.Icon")));
            this.Name = "AddInventory";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = " ";
            this.Load += new System.EventHandler(this.AddInventory_Load);
            ((System.ComponentModel.ISupportInitialize)(this.pcbItem)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.picQR)).EndInit();
            this.bunifuPanel1.ResumeLayout(false);
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private Bunifu.UI.WinForms.BunifuButton.BunifuButton bttnSave;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel6;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel5;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel4;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel3;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel2;
        private Bunifu.UI.WinForms.BunifuTextBox txtUP;
        private Bunifu.UI.WinForms.BunifuTextBox txtQuan;
        private Bunifu.UI.WinForms.BunifuTextBox txtPN;
        private Bunifu.UI.WinForms.BunifuDropdown dpCategory;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton bunifuButton1;
        private Bunifu.UI.WinForms.BunifuLabel txtMindeus;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel1;
        private Bunifu.UI.WinForms.BunifuDropdown dpSupplier;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel7;
        private System.Windows.Forms.PictureBox picQR;
        private Bunifu.UI.WinForms.BunifuPictureBox pcbItem;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnAddImage;
        private Bunifu.Framework.UI.BunifuElipse bunifuElipse1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnGenerate;
        private Bunifu.UI.WinForms.BunifuPanel bunifuPanel1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnPrint;
        private Bunifu.UI.WinForms.BunifuTextBox txtQRCode;
    }
}