namespace barcodescanner
{
    partial class BarcodeScannerApp
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(BarcodeScannerApp));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges7 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges6 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            this.cboCamera = new System.Windows.Forms.ComboBox();
            this.bunifuLabel2 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel1 = new Bunifu.UI.WinForms.BunifuLabel();
            this.lstScanHistory = new System.Windows.Forms.ListBox();
            this.goHome = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnExportHistory = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnClearHistory = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnStop = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnStart = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.txtInfo = new Bunifu.UI.WinForms.BunifuTextBox();
            this.Camera = new Bunifu.UI.WinForms.BunifuPictureBox();
            this.panelGrandtotal = new Bunifu.UI.WinForms.BunifuPanel();
            this.txtNumber = new Bunifu.UI.WinForms.BunifuLabel();
            this.txtTotal = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuElipse1 = new Bunifu.Framework.UI.BunifuElipse(this.components);
            this.pnlPayment = new Bunifu.UI.WinForms.BunifuShadowPanel();
            this.lblTotalTitle = new Bunifu.UI.WinForms.BunifuLabel();
            this.lblTotalAmount = new Bunifu.UI.WinForms.BunifuLabel();
            this.lblPayTitle = new Bunifu.UI.WinForms.BunifuLabel();
            this.txtCash = new Bunifu.UI.WinForms.BunifuTextBox();
            this.lblChangeTitle = new Bunifu.UI.WinForms.BunifuLabel();
            this.lblChange = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuButton1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnCheckout = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuPanel1 = new Bunifu.UI.WinForms.BunifuPanel();
            this.bunifuPanel2 = new Bunifu.UI.WinForms.BunifuPanel();
            ((System.ComponentModel.ISupportInitialize)(this.Camera)).BeginInit();
            this.panelGrandtotal.SuspendLayout();
            this.pnlPayment.SuspendLayout();
            this.bunifuPanel1.SuspendLayout();
            this.bunifuPanel2.SuspendLayout();
            this.SuspendLayout();
            // 
            // cboCamera
            // 
            this.cboCamera.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cboCamera.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.cboCamera.FormattingEnabled = true;
            this.cboCamera.Location = new System.Drawing.Point(105, 17);
            this.cboCamera.Name = "cboCamera";
            this.cboCamera.Size = new System.Drawing.Size(364, 29);
            this.cboCamera.TabIndex = 0;
            // 
            // bunifuLabel2
            // 
            this.bunifuLabel2.AllowParentOverrides = false;
            this.bunifuLabel2.AutoEllipsis = false;
            this.bunifuLabel2.CursorType = null;
            this.bunifuLabel2.Font = new System.Drawing.Font("Segoe UI Semibold", 14.25F, System.Drawing.FontStyle.Bold);
            this.bunifuLabel2.Location = new System.Drawing.Point(16, 100);
            this.bunifuLabel2.Name = "bunifuLabel2";
            this.bunifuLabel2.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel2.Size = new System.Drawing.Size(49, 25);
            this.bunifuLabel2.TabIndex = 5;
            this.bunifuLabel2.Text = "Code: ";
            this.bunifuLabel2.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel2.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel1
            // 
            this.bunifuLabel1.AllowParentOverrides = false;
            this.bunifuLabel1.AutoEllipsis = false;
            this.bunifuLabel1.CursorType = null;
            this.bunifuLabel1.Font = new System.Drawing.Font("Segoe UI Semibold", 14.25F, System.Drawing.FontStyle.Bold);
            this.bunifuLabel1.Location = new System.Drawing.Point(16, 17);
            this.bunifuLabel1.Name = "bunifuLabel1";
            this.bunifuLabel1.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel1.Size = new System.Drawing.Size(71, 25);
            this.bunifuLabel1.TabIndex = 6;
            this.bunifuLabel1.Text = "Camera: ";
            this.bunifuLabel1.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel1.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // lstScanHistory
            // 
            this.lstScanHistory.Font = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lstScanHistory.FormattingEnabled = true;
            this.lstScanHistory.ItemHeight = 17;
            this.lstScanHistory.Location = new System.Drawing.Point(487, 135);
            this.lstScanHistory.Name = "lstScanHistory";
            this.lstScanHistory.ScrollAlwaysVisible = true;
            this.lstScanHistory.Size = new System.Drawing.Size(400, 514);
            this.lstScanHistory.TabIndex = 8;
            this.lstScanHistory.DoubleClick += new System.EventHandler(this.lstScanHistory_DoubleClick);
            // 
            // goHome
            // 
            this.goHome.AllowAnimations = true;
            this.goHome.AllowMouseEffects = true;
            this.goHome.AllowToggling = false;
            this.goHome.AnimationSpeed = 200;
            this.goHome.AutoGenerateColors = false;
            this.goHome.AutoRoundBorders = false;
            this.goHome.AutoSizeLeftIcon = true;
            this.goHome.AutoSizeRightIcon = true;
            this.goHome.BackColor = System.Drawing.Color.Transparent;
            this.goHome.BackColor1 = System.Drawing.Color.White;
            this.goHome.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("goHome.BackgroundImage")));
            this.goHome.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.goHome.ButtonText = "Go back";
            this.goHome.ButtonTextMarginLeft = 0;
            this.goHome.ColorContrastOnClick = 45;
            this.goHome.ColorContrastOnHover = 45;
            this.goHome.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.goHome.CustomizableEdges = borderEdges1;
            this.goHome.DialogResult = System.Windows.Forms.DialogResult.None;
            this.goHome.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.goHome.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.goHome.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.goHome.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Hover;
            this.goHome.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.goHome.ForeColor = System.Drawing.Color.Black;
            this.goHome.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.goHome.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.goHome.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.goHome.IconMarginLeft = 11;
            this.goHome.IconPadding = 10;
            this.goHome.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.goHome.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.goHome.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.goHome.IconSize = 25;
            this.goHome.IdleBorderColor = System.Drawing.Color.Black;
            this.goHome.IdleBorderRadius = 10;
            this.goHome.IdleBorderThickness = 1;
            this.goHome.IdleFillColor = System.Drawing.Color.White;
            this.goHome.IdleIconLeftImage = null;
            this.goHome.IdleIconRightImage = null;
            this.goHome.IndicateFocus = false;
            this.goHome.Location = new System.Drawing.Point(793, 13);
            this.goHome.Name = "goHome";
            this.goHome.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.goHome.OnDisabledState.BorderRadius = 10;
            this.goHome.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.goHome.OnDisabledState.BorderThickness = 1;
            this.goHome.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.goHome.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.goHome.OnDisabledState.IconLeftImage = null;
            this.goHome.OnDisabledState.IconRightImage = null;
            this.goHome.onHoverState.BorderColor = System.Drawing.Color.Black;
            this.goHome.onHoverState.BorderRadius = 10;
            this.goHome.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.goHome.onHoverState.BorderThickness = 1;
            this.goHome.onHoverState.FillColor = System.Drawing.Color.DarkBlue;
            this.goHome.onHoverState.ForeColor = System.Drawing.Color.White;
            this.goHome.onHoverState.IconLeftImage = null;
            this.goHome.onHoverState.IconRightImage = null;
            this.goHome.OnIdleState.BorderColor = System.Drawing.Color.Black;
            this.goHome.OnIdleState.BorderRadius = 10;
            this.goHome.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.goHome.OnIdleState.BorderThickness = 1;
            this.goHome.OnIdleState.FillColor = System.Drawing.Color.White;
            this.goHome.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.goHome.OnIdleState.IconLeftImage = null;
            this.goHome.OnIdleState.IconRightImage = null;
            this.goHome.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.goHome.OnPressedState.BorderRadius = 10;
            this.goHome.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.goHome.OnPressedState.BorderThickness = 1;
            this.goHome.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.goHome.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.goHome.OnPressedState.IconLeftImage = null;
            this.goHome.OnPressedState.IconRightImage = null;
            this.goHome.Size = new System.Drawing.Size(94, 29);
            this.goHome.TabIndex = 11;
            this.goHome.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.goHome.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.goHome.TextMarginLeft = 0;
            this.goHome.TextPadding = new System.Windows.Forms.Padding(0);
            this.goHome.UseDefaultRadiusAndThickness = true;
            this.goHome.Click += new System.EventHandler(this.goHome_Click);
            // 
            // btnExportHistory
            // 
            this.btnExportHistory.AllowAnimations = true;
            this.btnExportHistory.AllowMouseEffects = true;
            this.btnExportHistory.AllowToggling = false;
            this.btnExportHistory.AnimationSpeed = 200;
            this.btnExportHistory.AutoGenerateColors = false;
            this.btnExportHistory.AutoRoundBorders = false;
            this.btnExportHistory.AutoSizeLeftIcon = true;
            this.btnExportHistory.AutoSizeRightIcon = true;
            this.btnExportHistory.BackColor = System.Drawing.Color.Transparent;
            this.btnExportHistory.BackColor1 = System.Drawing.Color.White;
            this.btnExportHistory.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnExportHistory.BackgroundImage")));
            this.btnExportHistory.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnExportHistory.ButtonText = "Export";
            this.btnExportHistory.ButtonTextMarginLeft = 0;
            this.btnExportHistory.ColorContrastOnClick = 45;
            this.btnExportHistory.ColorContrastOnHover = 45;
            this.btnExportHistory.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.btnExportHistory.CustomizableEdges = borderEdges2;
            this.btnExportHistory.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnExportHistory.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnExportHistory.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnExportHistory.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnExportHistory.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Hover;
            this.btnExportHistory.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btnExportHistory.ForeColor = System.Drawing.Color.Black;
            this.btnExportHistory.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnExportHistory.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnExportHistory.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnExportHistory.IconMarginLeft = 11;
            this.btnExportHistory.IconPadding = 10;
            this.btnExportHistory.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnExportHistory.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnExportHistory.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnExportHistory.IconSize = 25;
            this.btnExportHistory.IdleBorderColor = System.Drawing.Color.Black;
            this.btnExportHistory.IdleBorderRadius = 10;
            this.btnExportHistory.IdleBorderThickness = 1;
            this.btnExportHistory.IdleFillColor = System.Drawing.Color.White;
            this.btnExportHistory.IdleIconLeftImage = null;
            this.btnExportHistory.IdleIconRightImage = null;
            this.btnExportHistory.IndicateFocus = false;
            this.btnExportHistory.Location = new System.Drawing.Point(487, 655);
            this.btnExportHistory.Name = "btnExportHistory";
            this.btnExportHistory.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnExportHistory.OnDisabledState.BorderRadius = 10;
            this.btnExportHistory.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnExportHistory.OnDisabledState.BorderThickness = 1;
            this.btnExportHistory.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnExportHistory.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnExportHistory.OnDisabledState.IconLeftImage = null;
            this.btnExportHistory.OnDisabledState.IconRightImage = null;
            this.btnExportHistory.onHoverState.BorderColor = System.Drawing.Color.Black;
            this.btnExportHistory.onHoverState.BorderRadius = 10;
            this.btnExportHistory.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnExportHistory.onHoverState.BorderThickness = 1;
            this.btnExportHistory.onHoverState.FillColor = System.Drawing.Color.DarkBlue;
            this.btnExportHistory.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnExportHistory.onHoverState.IconLeftImage = null;
            this.btnExportHistory.onHoverState.IconRightImage = null;
            this.btnExportHistory.OnIdleState.BorderColor = System.Drawing.Color.Black;
            this.btnExportHistory.OnIdleState.BorderRadius = 10;
            this.btnExportHistory.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnExportHistory.OnIdleState.BorderThickness = 1;
            this.btnExportHistory.OnIdleState.FillColor = System.Drawing.Color.White;
            this.btnExportHistory.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.btnExportHistory.OnIdleState.IconLeftImage = null;
            this.btnExportHistory.OnIdleState.IconRightImage = null;
            this.btnExportHistory.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnExportHistory.OnPressedState.BorderRadius = 10;
            this.btnExportHistory.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnExportHistory.OnPressedState.BorderThickness = 1;
            this.btnExportHistory.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnExportHistory.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnExportHistory.OnPressedState.IconLeftImage = null;
            this.btnExportHistory.OnPressedState.IconRightImage = null;
            this.btnExportHistory.Size = new System.Drawing.Size(94, 29);
            this.btnExportHistory.TabIndex = 10;
            this.btnExportHistory.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnExportHistory.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnExportHistory.TextMarginLeft = 0;
            this.btnExportHistory.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnExportHistory.UseDefaultRadiusAndThickness = true;
            this.btnExportHistory.Click += new System.EventHandler(this.btnExportHistory_Click);
            // 
            // btnClearHistory
            // 
            this.btnClearHistory.AllowAnimations = true;
            this.btnClearHistory.AllowMouseEffects = true;
            this.btnClearHistory.AllowToggling = false;
            this.btnClearHistory.AnimationSpeed = 200;
            this.btnClearHistory.AutoGenerateColors = false;
            this.btnClearHistory.AutoRoundBorders = false;
            this.btnClearHistory.AutoSizeLeftIcon = true;
            this.btnClearHistory.AutoSizeRightIcon = true;
            this.btnClearHistory.BackColor = System.Drawing.Color.Transparent;
            this.btnClearHistory.BackColor1 = System.Drawing.Color.White;
            this.btnClearHistory.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnClearHistory.BackgroundImage")));
            this.btnClearHistory.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnClearHistory.ButtonText = "Clear";
            this.btnClearHistory.ButtonTextMarginLeft = 0;
            this.btnClearHistory.ColorContrastOnClick = 45;
            this.btnClearHistory.ColorContrastOnHover = 45;
            this.btnClearHistory.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.btnClearHistory.CustomizableEdges = borderEdges3;
            this.btnClearHistory.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnClearHistory.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnClearHistory.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnClearHistory.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnClearHistory.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Hover;
            this.btnClearHistory.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btnClearHistory.ForeColor = System.Drawing.Color.Black;
            this.btnClearHistory.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnClearHistory.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnClearHistory.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnClearHistory.IconMarginLeft = 11;
            this.btnClearHistory.IconPadding = 10;
            this.btnClearHistory.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnClearHistory.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnClearHistory.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnClearHistory.IconSize = 25;
            this.btnClearHistory.IdleBorderColor = System.Drawing.Color.Black;
            this.btnClearHistory.IdleBorderRadius = 10;
            this.btnClearHistory.IdleBorderThickness = 1;
            this.btnClearHistory.IdleFillColor = System.Drawing.Color.White;
            this.btnClearHistory.IdleIconLeftImage = null;
            this.btnClearHistory.IdleIconRightImage = null;
            this.btnClearHistory.IndicateFocus = false;
            this.btnClearHistory.Location = new System.Drawing.Point(805, 655);
            this.btnClearHistory.Name = "btnClearHistory";
            this.btnClearHistory.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnClearHistory.OnDisabledState.BorderRadius = 10;
            this.btnClearHistory.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnClearHistory.OnDisabledState.BorderThickness = 1;
            this.btnClearHistory.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnClearHistory.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnClearHistory.OnDisabledState.IconLeftImage = null;
            this.btnClearHistory.OnDisabledState.IconRightImage = null;
            this.btnClearHistory.onHoverState.BorderColor = System.Drawing.Color.Black;
            this.btnClearHistory.onHoverState.BorderRadius = 10;
            this.btnClearHistory.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnClearHistory.onHoverState.BorderThickness = 1;
            this.btnClearHistory.onHoverState.FillColor = System.Drawing.Color.DarkBlue;
            this.btnClearHistory.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnClearHistory.onHoverState.IconLeftImage = null;
            this.btnClearHistory.onHoverState.IconRightImage = null;
            this.btnClearHistory.OnIdleState.BorderColor = System.Drawing.Color.Black;
            this.btnClearHistory.OnIdleState.BorderRadius = 10;
            this.btnClearHistory.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnClearHistory.OnIdleState.BorderThickness = 1;
            this.btnClearHistory.OnIdleState.FillColor = System.Drawing.Color.White;
            this.btnClearHistory.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.btnClearHistory.OnIdleState.IconLeftImage = null;
            this.btnClearHistory.OnIdleState.IconRightImage = null;
            this.btnClearHistory.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnClearHistory.OnPressedState.BorderRadius = 10;
            this.btnClearHistory.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnClearHistory.OnPressedState.BorderThickness = 1;
            this.btnClearHistory.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnClearHistory.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnClearHistory.OnPressedState.IconLeftImage = null;
            this.btnClearHistory.OnPressedState.IconRightImage = null;
            this.btnClearHistory.Size = new System.Drawing.Size(82, 29);
            this.btnClearHistory.TabIndex = 9;
            this.btnClearHistory.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnClearHistory.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnClearHistory.TextMarginLeft = 0;
            this.btnClearHistory.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnClearHistory.UseDefaultRadiusAndThickness = true;
            this.btnClearHistory.Click += new System.EventHandler(this.btnClearHistory_Click);
            // 
            // btnStop
            // 
            this.btnStop.AllowAnimations = true;
            this.btnStop.AllowMouseEffects = true;
            this.btnStop.AllowToggling = false;
            this.btnStop.AnimationSpeed = 200;
            this.btnStop.AutoGenerateColors = false;
            this.btnStop.AutoRoundBorders = false;
            this.btnStop.AutoSizeLeftIcon = true;
            this.btnStop.AutoSizeRightIcon = true;
            this.btnStop.BackColor = System.Drawing.Color.Transparent;
            this.btnStop.BackColor1 = System.Drawing.Color.White;
            this.btnStop.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnStop.BackgroundImage")));
            this.btnStop.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnStop.ButtonText = "Stop Camera";
            this.btnStop.ButtonTextMarginLeft = 0;
            this.btnStop.ColorContrastOnClick = 45;
            this.btnStop.ColorContrastOnHover = 45;
            this.btnStop.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.btnStop.CustomizableEdges = borderEdges4;
            this.btnStop.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnStop.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnStop.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnStop.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnStop.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Hover;
            this.btnStop.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btnStop.ForeColor = System.Drawing.Color.Black;
            this.btnStop.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnStop.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnStop.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnStop.IconMarginLeft = 11;
            this.btnStop.IconPadding = 10;
            this.btnStop.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnStop.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnStop.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnStop.IconSize = 25;
            this.btnStop.IdleBorderColor = System.Drawing.Color.Black;
            this.btnStop.IdleBorderRadius = 10;
            this.btnStop.IdleBorderThickness = 1;
            this.btnStop.IdleFillColor = System.Drawing.Color.White;
            this.btnStop.IdleIconLeftImage = null;
            this.btnStop.IdleIconRightImage = null;
            this.btnStop.IndicateFocus = false;
            this.btnStop.Location = new System.Drawing.Point(16, 608);
            this.btnStop.Name = "btnStop";
            this.btnStop.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnStop.OnDisabledState.BorderRadius = 10;
            this.btnStop.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnStop.OnDisabledState.BorderThickness = 1;
            this.btnStop.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnStop.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnStop.OnDisabledState.IconLeftImage = null;
            this.btnStop.OnDisabledState.IconRightImage = null;
            this.btnStop.onHoverState.BorderColor = System.Drawing.Color.Black;
            this.btnStop.onHoverState.BorderRadius = 10;
            this.btnStop.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnStop.onHoverState.BorderThickness = 1;
            this.btnStop.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(128)))), ((int)(((byte)(128)))));
            this.btnStop.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.btnStop.onHoverState.IconLeftImage = null;
            this.btnStop.onHoverState.IconRightImage = null;
            this.btnStop.OnIdleState.BorderColor = System.Drawing.Color.Black;
            this.btnStop.OnIdleState.BorderRadius = 10;
            this.btnStop.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnStop.OnIdleState.BorderThickness = 1;
            this.btnStop.OnIdleState.FillColor = System.Drawing.Color.White;
            this.btnStop.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.btnStop.OnIdleState.IconLeftImage = null;
            this.btnStop.OnIdleState.IconRightImage = null;
            this.btnStop.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnStop.OnPressedState.BorderRadius = 10;
            this.btnStop.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnStop.OnPressedState.BorderThickness = 1;
            this.btnStop.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(128)))), ((int)(((byte)(128)))));
            this.btnStop.OnPressedState.ForeColor = System.Drawing.Color.Black;
            this.btnStop.OnPressedState.IconLeftImage = null;
            this.btnStop.OnPressedState.IconRightImage = null;
            this.btnStop.Size = new System.Drawing.Size(453, 41);
            this.btnStop.TabIndex = 7;
            this.btnStop.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnStop.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnStop.TextMarginLeft = 0;
            this.btnStop.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnStop.UseDefaultRadiusAndThickness = true;
            this.btnStop.Click += new System.EventHandler(this.btnStop_Click);
            // 
            // btnStart
            // 
            this.btnStart.AllowAnimations = true;
            this.btnStart.AllowMouseEffects = true;
            this.btnStart.AllowToggling = false;
            this.btnStart.AnimationSpeed = 200;
            this.btnStart.AutoGenerateColors = false;
            this.btnStart.AutoRoundBorders = false;
            this.btnStart.AutoSizeLeftIcon = true;
            this.btnStart.AutoSizeRightIcon = true;
            this.btnStart.BackColor = System.Drawing.Color.Transparent;
            this.btnStart.BackColor1 = System.Drawing.Color.White;
            this.btnStart.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnStart.BackgroundImage")));
            this.btnStart.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnStart.ButtonText = "Start";
            this.btnStart.ButtonTextMarginLeft = 0;
            this.btnStart.ColorContrastOnClick = 45;
            this.btnStart.ColorContrastOnHover = 45;
            this.btnStart.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.btnStart.CustomizableEdges = borderEdges5;
            this.btnStart.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnStart.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnStart.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnStart.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnStart.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Hover;
            this.btnStart.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btnStart.ForeColor = System.Drawing.Color.Black;
            this.btnStart.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnStart.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnStart.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnStart.IconMarginLeft = 11;
            this.btnStart.IconPadding = 10;
            this.btnStart.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnStart.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnStart.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnStart.IconSize = 25;
            this.btnStart.IdleBorderColor = System.Drawing.Color.Black;
            this.btnStart.IdleBorderRadius = 10;
            this.btnStart.IdleBorderThickness = 1;
            this.btnStart.IdleFillColor = System.Drawing.Color.White;
            this.btnStart.IdleIconLeftImage = null;
            this.btnStart.IdleIconRightImage = null;
            this.btnStart.IndicateFocus = false;
            this.btnStart.Location = new System.Drawing.Point(16, 608);
            this.btnStart.Name = "btnStart";
            this.btnStart.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnStart.OnDisabledState.BorderRadius = 10;
            this.btnStart.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnStart.OnDisabledState.BorderThickness = 1;
            this.btnStart.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnStart.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnStart.OnDisabledState.IconLeftImage = null;
            this.btnStart.OnDisabledState.IconRightImage = null;
            this.btnStart.onHoverState.BorderColor = System.Drawing.SystemColors.Control;
            this.btnStart.onHoverState.BorderRadius = 10;
            this.btnStart.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnStart.onHoverState.BorderThickness = 1;
            this.btnStart.onHoverState.FillColor = System.Drawing.Color.DarkBlue;
            this.btnStart.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnStart.onHoverState.IconLeftImage = null;
            this.btnStart.onHoverState.IconRightImage = null;
            this.btnStart.OnIdleState.BorderColor = System.Drawing.Color.Black;
            this.btnStart.OnIdleState.BorderRadius = 10;
            this.btnStart.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnStart.OnIdleState.BorderThickness = 1;
            this.btnStart.OnIdleState.FillColor = System.Drawing.Color.White;
            this.btnStart.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.btnStart.OnIdleState.IconLeftImage = null;
            this.btnStart.OnIdleState.IconRightImage = null;
            this.btnStart.OnPressedState.BorderColor = System.Drawing.SystemColors.Control;
            this.btnStart.OnPressedState.BorderRadius = 10;
            this.btnStart.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnStart.OnPressedState.BorderThickness = 1;
            this.btnStart.OnPressedState.FillColor = System.Drawing.Color.DarkBlue;
            this.btnStart.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnStart.OnPressedState.IconLeftImage = null;
            this.btnStart.OnPressedState.IconRightImage = null;
            this.btnStart.Size = new System.Drawing.Size(453, 41);
            this.btnStart.TabIndex = 4;
            this.btnStart.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnStart.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnStart.TextMarginLeft = 0;
            this.btnStart.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnStart.UseDefaultRadiusAndThickness = true;
            this.btnStart.Click += new System.EventHandler(this.btnStart_Click);
            // 
            // txtInfo
            // 
            this.txtInfo.AcceptsReturn = false;
            this.txtInfo.AcceptsTab = false;
            this.txtInfo.AnimationSpeed = 200;
            this.txtInfo.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtInfo.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtInfo.BackColor = System.Drawing.Color.Transparent;
            this.txtInfo.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtInfo.BackgroundImage")));
            this.txtInfo.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtInfo.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtInfo.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtInfo.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtInfo.BorderRadius = 12;
            this.txtInfo.BorderThickness = 1;
            this.txtInfo.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtInfo.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtInfo.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtInfo.DefaultText = "";
            this.txtInfo.FillColor = System.Drawing.Color.White;
            this.txtInfo.HideSelection = true;
            this.txtInfo.IconLeft = null;
            this.txtInfo.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtInfo.IconPadding = 10;
            this.txtInfo.IconRight = null;
            this.txtInfo.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtInfo.Lines = new string[0];
            this.txtInfo.Location = new System.Drawing.Point(71, 92);
            this.txtInfo.MaxLength = 32767;
            this.txtInfo.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtInfo.Modified = false;
            this.txtInfo.Multiline = false;
            this.txtInfo.Name = "txtInfo";
            stateProperties1.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtInfo.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtInfo.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtInfo.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtInfo.OnIdleState = stateProperties4;
            this.txtInfo.Padding = new System.Windows.Forms.Padding(3);
            this.txtInfo.PasswordChar = '\0';
            this.txtInfo.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtInfo.PlaceholderText = "Enter text";
            this.txtInfo.ReadOnly = false;
            this.txtInfo.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtInfo.SelectedText = "";
            this.txtInfo.SelectionLength = 0;
            this.txtInfo.SelectionStart = 0;
            this.txtInfo.ShortcutsEnabled = true;
            this.txtInfo.Size = new System.Drawing.Size(294, 37);
            this.txtInfo.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtInfo.TabIndex = 3;
            this.txtInfo.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtInfo.TextMarginBottom = 0;
            this.txtInfo.TextMarginLeft = 3;
            this.txtInfo.TextMarginTop = 0;
            this.txtInfo.TextPlaceholder = "Enter text";
            this.txtInfo.UseSystemPasswordChar = false;
            this.txtInfo.WordWrap = true;
            // 
            // Camera
            // 
            this.Camera.AllowFocused = false;
            this.Camera.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.Camera.AutoSizeHeight = true;
            this.Camera.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Center;
            this.Camera.BorderRadius = 0;
            this.Camera.ErrorImage = null;
            this.Camera.Image = ((System.Drawing.Image)(resources.GetObject("Camera.Image")));
            this.Camera.InitialImage = null;
            this.Camera.IsCircle = true;
            this.Camera.Location = new System.Drawing.Point(16, 135);
            this.Camera.Name = "Camera";
            this.Camera.Size = new System.Drawing.Size(453, 453);
            this.Camera.SizeMode = System.Windows.Forms.PictureBoxSizeMode.CenterImage;
            this.Camera.TabIndex = 2;
            this.Camera.TabStop = false;
            this.Camera.Type = Bunifu.UI.WinForms.BunifuPictureBox.Types.Square;
            // 
            // panelGrandtotal
            // 
            this.panelGrandtotal.BackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(192)))));
            this.panelGrandtotal.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("panelGrandtotal.BackgroundImage")));
            this.panelGrandtotal.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.panelGrandtotal.BorderColor = System.Drawing.Color.Transparent;
            this.panelGrandtotal.BorderRadius = 20;
            this.panelGrandtotal.BorderThickness = 1;
            this.panelGrandtotal.Controls.Add(this.txtNumber);
            this.panelGrandtotal.Controls.Add(this.txtTotal);
            this.panelGrandtotal.Location = new System.Drawing.Point(487, 52);
            this.panelGrandtotal.Name = "panelGrandtotal";
            this.panelGrandtotal.ShowBorders = true;
            this.panelGrandtotal.Size = new System.Drawing.Size(400, 77);
            this.panelGrandtotal.TabIndex = 12;
            // 
            // txtNumber
            // 
            this.txtNumber.AllowParentOverrides = false;
            this.txtNumber.AutoEllipsis = false;
            this.txtNumber.CursorType = null;
            this.txtNumber.Font = new System.Drawing.Font("Verdana", 20.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtNumber.ForeColor = System.Drawing.Color.Transparent;
            this.txtNumber.Location = new System.Drawing.Point(218, 25);
            this.txtNumber.Name = "txtNumber";
            this.txtNumber.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.txtNumber.Size = new System.Drawing.Size(67, 32);
            this.txtNumber.TabIndex = 1;
            this.txtNumber.Text = "0.00";
            this.txtNumber.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.txtNumber.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            this.txtNumber.Click += new System.EventHandler(this.txtNumber_Click);
            // 
            // txtTotal
            // 
            this.txtTotal.AllowParentOverrides = false;
            this.txtTotal.AutoEllipsis = false;
            this.txtTotal.Cursor = System.Windows.Forms.Cursors.Default;
            this.txtTotal.CursorType = System.Windows.Forms.Cursors.Default;
            this.txtTotal.Font = new System.Drawing.Font("Verdana", 20.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtTotal.ForeColor = System.Drawing.Color.Transparent;
            this.txtTotal.Location = new System.Drawing.Point(19, 25);
            this.txtTotal.Name = "txtTotal";
            this.txtTotal.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.txtTotal.Size = new System.Drawing.Size(172, 32);
            this.txtTotal.TabIndex = 0;
            this.txtTotal.Text = "Total Price:";
            this.txtTotal.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.txtTotal.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuElipse1
            // 
            this.bunifuElipse1.ElipseRadius = 50;
            this.bunifuElipse1.TargetControl = this;
            // 
            // pnlPayment
            // 
            this.pnlPayment.BackColor = System.Drawing.Color.Transparent;
            this.pnlPayment.BorderColor = System.Drawing.Color.WhiteSmoke;
            this.pnlPayment.BorderRadius = 1;
            this.pnlPayment.BorderThickness = 1;
            this.pnlPayment.Controls.Add(this.bunifuButton1);
            this.pnlPayment.Controls.Add(this.lblChangeTitle);
            this.pnlPayment.Controls.Add(this.txtCash);
            this.pnlPayment.Controls.Add(this.lblPayTitle);
            this.pnlPayment.Controls.Add(this.lblTotalTitle);
            this.pnlPayment.Controls.Add(this.bunifuPanel1);
            this.pnlPayment.Controls.Add(this.bunifuPanel2);
            this.pnlPayment.FillStyle = Bunifu.UI.WinForms.BunifuShadowPanel.FillStyles.Solid;
            this.pnlPayment.GradientMode = Bunifu.UI.WinForms.BunifuShadowPanel.GradientModes.Vertical;
            this.pnlPayment.Location = new System.Drawing.Point(906, 52);
            this.pnlPayment.Name = "pnlPayment";
            this.pnlPayment.PanelColor = System.Drawing.Color.WhiteSmoke;
            this.pnlPayment.PanelColor2 = System.Drawing.Color.WhiteSmoke;
            this.pnlPayment.ShadowColor = System.Drawing.Color.DarkGray;
            this.pnlPayment.ShadowDept = 2;
            this.pnlPayment.ShadowDepth = 5;
            this.pnlPayment.ShadowStyle = Bunifu.UI.WinForms.BunifuShadowPanel.ShadowStyles.Surrounded;
            this.pnlPayment.ShadowTopLeftVisible = false;
            this.pnlPayment.Size = new System.Drawing.Size(414, 596);
            this.pnlPayment.Style = Bunifu.UI.WinForms.BunifuShadowPanel.BevelStyles.Flat;
            this.pnlPayment.TabIndex = 16;
            this.pnlPayment.Visible = false;
            // 
            // lblTotalTitle
            // 
            this.lblTotalTitle.AllowParentOverrides = false;
            this.lblTotalTitle.AutoEllipsis = false;
            this.lblTotalTitle.CursorType = null;
            this.lblTotalTitle.Font = new System.Drawing.Font("Segoe UI Semibold", 14.25F, System.Drawing.FontStyle.Bold);
            this.lblTotalTitle.Location = new System.Drawing.Point(28, 34);
            this.lblTotalTitle.Name = "lblTotalTitle";
            this.lblTotalTitle.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.lblTotalTitle.Size = new System.Drawing.Size(140, 25);
            this.lblTotalTitle.TabIndex = 17;
            this.lblTotalTitle.Text = "Total Ammount:";
            this.lblTotalTitle.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.lblTotalTitle.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // lblTotalAmount
            // 
            this.lblTotalAmount.AllowParentOverrides = false;
            this.lblTotalAmount.AutoEllipsis = false;
            this.lblTotalAmount.CursorType = null;
            this.lblTotalAmount.Font = new System.Drawing.Font("Segoe UI Semibold", 14.25F, System.Drawing.FontStyle.Bold);
            this.lblTotalAmount.ForeColor = System.Drawing.SystemColors.Control;
            this.lblTotalAmount.Location = new System.Drawing.Point(34, 14);
            this.lblTotalAmount.Name = "lblTotalAmount";
            this.lblTotalAmount.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.lblTotalAmount.Size = new System.Drawing.Size(168, 25);
            this.lblTotalAmount.TabIndex = 18;
            this.lblTotalAmount.Text = "The total Ammount";
            this.lblTotalAmount.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.lblTotalAmount.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // lblPayTitle
            // 
            this.lblPayTitle.AllowParentOverrides = false;
            this.lblPayTitle.AutoEllipsis = false;
            this.lblPayTitle.CursorType = null;
            this.lblPayTitle.Font = new System.Drawing.Font("Segoe UI Semibold", 14.25F, System.Drawing.FontStyle.Bold);
            this.lblPayTitle.Location = new System.Drawing.Point(28, 162);
            this.lblPayTitle.Name = "lblPayTitle";
            this.lblPayTitle.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.lblPayTitle.Size = new System.Drawing.Size(169, 25);
            this.lblPayTitle.TabIndex = 19;
            this.lblPayTitle.Text = "Customer Payment:";
            this.lblPayTitle.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.lblPayTitle.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // txtCash
            // 
            this.txtCash.AcceptsReturn = false;
            this.txtCash.AcceptsTab = false;
            this.txtCash.AnimationSpeed = 200;
            this.txtCash.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtCash.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtCash.BackColor = System.Drawing.Color.Transparent;
            this.txtCash.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtCash.BackgroundImage")));
            this.txtCash.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtCash.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtCash.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtCash.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtCash.BorderRadius = 12;
            this.txtCash.BorderThickness = 1;
            this.txtCash.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtCash.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtCash.DefaultFont = new System.Drawing.Font("Segoe UI", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtCash.DefaultText = "";
            this.txtCash.FillColor = System.Drawing.Color.White;
            this.txtCash.HideSelection = true;
            this.txtCash.IconLeft = null;
            this.txtCash.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtCash.IconPadding = 10;
            this.txtCash.IconRight = null;
            this.txtCash.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtCash.Lines = new string[0];
            this.txtCash.Location = new System.Drawing.Point(28, 193);
            this.txtCash.MaxLength = 32767;
            this.txtCash.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtCash.Modified = false;
            this.txtCash.Multiline = false;
            this.txtCash.Name = "txtCash";
            stateProperties5.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtCash.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtCash.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtCash.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Silver;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Empty;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtCash.OnIdleState = stateProperties8;
            this.txtCash.Padding = new System.Windows.Forms.Padding(3);
            this.txtCash.PasswordChar = '\0';
            this.txtCash.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtCash.PlaceholderText = "Enter text";
            this.txtCash.ReadOnly = false;
            this.txtCash.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtCash.SelectedText = "";
            this.txtCash.SelectionLength = 0;
            this.txtCash.SelectionStart = 0;
            this.txtCash.ShortcutsEnabled = true;
            this.txtCash.Size = new System.Drawing.Size(372, 40);
            this.txtCash.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtCash.TabIndex = 17;
            this.txtCash.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtCash.TextMarginBottom = 0;
            this.txtCash.TextMarginLeft = 3;
            this.txtCash.TextMarginTop = 0;
            this.txtCash.TextPlaceholder = "Enter text";
            this.txtCash.UseSystemPasswordChar = false;
            this.txtCash.WordWrap = true;
            this.txtCash.TextChange += new System.EventHandler(this.txtCash_TextChange);
            // 
            // lblChangeTitle
            // 
            this.lblChangeTitle.AllowParentOverrides = false;
            this.lblChangeTitle.AutoEllipsis = false;
            this.lblChangeTitle.CursorType = null;
            this.lblChangeTitle.Font = new System.Drawing.Font("Segoe UI Semibold", 14.25F, System.Drawing.FontStyle.Bold);
            this.lblChangeTitle.Location = new System.Drawing.Point(28, 357);
            this.lblChangeTitle.Name = "lblChangeTitle";
            this.lblChangeTitle.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.lblChangeTitle.Size = new System.Drawing.Size(70, 25);
            this.lblChangeTitle.TabIndex = 20;
            this.lblChangeTitle.Text = "Change:";
            this.lblChangeTitle.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.lblChangeTitle.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // lblChange
            // 
            this.lblChange.AllowParentOverrides = false;
            this.lblChange.AutoEllipsis = false;
            this.lblChange.CursorType = null;
            this.lblChange.Font = new System.Drawing.Font("Segoe UI Semibold", 14.25F, System.Drawing.FontStyle.Bold);
            this.lblChange.ForeColor = System.Drawing.SystemColors.Control;
            this.lblChange.Location = new System.Drawing.Point(33, 15);
            this.lblChange.Name = "lblChange";
            this.lblChange.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.lblChange.Size = new System.Drawing.Size(155, 25);
            this.lblChange.TabIndex = 21;
            this.lblChange.Text = "The actual change";
            this.lblChange.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.lblChange.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuButton1
            // 
            this.bunifuButton1.AllowAnimations = true;
            this.bunifuButton1.AllowMouseEffects = true;
            this.bunifuButton1.AllowToggling = false;
            this.bunifuButton1.AnimationSpeed = 200;
            this.bunifuButton1.AutoGenerateColors = false;
            this.bunifuButton1.AutoRoundBorders = false;
            this.bunifuButton1.AutoSizeLeftIcon = true;
            this.bunifuButton1.AutoSizeRightIcon = true;
            this.bunifuButton1.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButton1.BackColor1 = System.Drawing.Color.White;
            this.bunifuButton1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton1.BackgroundImage")));
            this.bunifuButton1.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.ButtonText = "Confirm Payment";
            this.bunifuButton1.ButtonTextMarginLeft = 0;
            this.bunifuButton1.ColorContrastOnClick = 45;
            this.bunifuButton1.ColorContrastOnHover = 45;
            this.bunifuButton1.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges7.BottomLeft = true;
            borderEdges7.BottomRight = true;
            borderEdges7.TopLeft = true;
            borderEdges7.TopRight = true;
            this.bunifuButton1.CustomizableEdges = borderEdges7;
            this.bunifuButton1.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButton1.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton1.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton1.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton1.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Hover;
            this.bunifuButton1.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuButton1.ForeColor = System.Drawing.Color.Black;
            this.bunifuButton1.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButton1.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton1.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bunifuButton1.IconMarginLeft = 11;
            this.bunifuButton1.IconPadding = 10;
            this.bunifuButton1.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButton1.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton1.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bunifuButton1.IconSize = 25;
            this.bunifuButton1.IdleBorderColor = System.Drawing.Color.Black;
            this.bunifuButton1.IdleBorderRadius = 10;
            this.bunifuButton1.IdleBorderThickness = 1;
            this.bunifuButton1.IdleFillColor = System.Drawing.Color.White;
            this.bunifuButton1.IdleIconLeftImage = null;
            this.bunifuButton1.IdleIconRightImage = null;
            this.bunifuButton1.IndicateFocus = false;
            this.bunifuButton1.Location = new System.Drawing.Point(62, 452);
            this.bunifuButton1.Name = "bunifuButton1";
            this.bunifuButton1.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton1.OnDisabledState.BorderRadius = 10;
            this.bunifuButton1.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.OnDisabledState.BorderThickness = 1;
            this.bunifuButton1.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton1.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton1.OnDisabledState.IconLeftImage = null;
            this.bunifuButton1.OnDisabledState.IconRightImage = null;
            this.bunifuButton1.onHoverState.BorderColor = System.Drawing.Color.Black;
            this.bunifuButton1.onHoverState.BorderRadius = 10;
            this.bunifuButton1.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.onHoverState.BorderThickness = 1;
            this.bunifuButton1.onHoverState.FillColor = System.Drawing.Color.DarkBlue;
            this.bunifuButton1.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton1.onHoverState.IconLeftImage = null;
            this.bunifuButton1.onHoverState.IconRightImage = null;
            this.bunifuButton1.OnIdleState.BorderColor = System.Drawing.Color.Black;
            this.bunifuButton1.OnIdleState.BorderRadius = 10;
            this.bunifuButton1.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.OnIdleState.BorderThickness = 1;
            this.bunifuButton1.OnIdleState.FillColor = System.Drawing.Color.White;
            this.bunifuButton1.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.bunifuButton1.OnIdleState.IconLeftImage = null;
            this.bunifuButton1.OnIdleState.IconRightImage = null;
            this.bunifuButton1.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton1.OnPressedState.BorderRadius = 10;
            this.bunifuButton1.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.OnPressedState.BorderThickness = 1;
            this.bunifuButton1.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton1.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton1.OnPressedState.IconLeftImage = null;
            this.bunifuButton1.OnPressedState.IconRightImage = null;
            this.bunifuButton1.Size = new System.Drawing.Size(292, 49);
            this.bunifuButton1.TabIndex = 17;
            this.bunifuButton1.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuButton1.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButton1.TextMarginLeft = 0;
            this.bunifuButton1.TextPadding = new System.Windows.Forms.Padding(0);
            this.bunifuButton1.UseDefaultRadiusAndThickness = true;
            this.bunifuButton1.Click += new System.EventHandler(this.bunifuButton1_Click);
            // 
            // btnCheckout
            // 
            this.btnCheckout.AllowAnimations = true;
            this.btnCheckout.AllowMouseEffects = true;
            this.btnCheckout.AllowToggling = false;
            this.btnCheckout.AnimationSpeed = 200;
            this.btnCheckout.AutoGenerateColors = false;
            this.btnCheckout.AutoRoundBorders = false;
            this.btnCheckout.AutoSizeLeftIcon = true;
            this.btnCheckout.AutoSizeRightIcon = true;
            this.btnCheckout.BackColor = System.Drawing.Color.Transparent;
            this.btnCheckout.BackColor1 = System.Drawing.Color.White;
            this.btnCheckout.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnCheckout.BackgroundImage")));
            this.btnCheckout.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCheckout.ButtonText = "Checkout";
            this.btnCheckout.ButtonTextMarginLeft = 0;
            this.btnCheckout.ColorContrastOnClick = 45;
            this.btnCheckout.ColorContrastOnHover = 45;
            this.btnCheckout.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges6.BottomLeft = true;
            borderEdges6.BottomRight = true;
            borderEdges6.TopLeft = true;
            borderEdges6.TopRight = true;
            this.btnCheckout.CustomizableEdges = borderEdges6;
            this.btnCheckout.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnCheckout.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnCheckout.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnCheckout.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnCheckout.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Hover;
            this.btnCheckout.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btnCheckout.ForeColor = System.Drawing.Color.Black;
            this.btnCheckout.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnCheckout.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnCheckout.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnCheckout.IconMarginLeft = 11;
            this.btnCheckout.IconPadding = 10;
            this.btnCheckout.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnCheckout.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnCheckout.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnCheckout.IconSize = 25;
            this.btnCheckout.IdleBorderColor = System.Drawing.Color.Black;
            this.btnCheckout.IdleBorderRadius = 10;
            this.btnCheckout.IdleBorderThickness = 1;
            this.btnCheckout.IdleFillColor = System.Drawing.Color.White;
            this.btnCheckout.IdleIconLeftImage = null;
            this.btnCheckout.IdleIconRightImage = null;
            this.btnCheckout.IndicateFocus = false;
            this.btnCheckout.Location = new System.Drawing.Point(587, 655);
            this.btnCheckout.Name = "btnCheckout";
            this.btnCheckout.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnCheckout.OnDisabledState.BorderRadius = 10;
            this.btnCheckout.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCheckout.OnDisabledState.BorderThickness = 1;
            this.btnCheckout.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnCheckout.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnCheckout.OnDisabledState.IconLeftImage = null;
            this.btnCheckout.OnDisabledState.IconRightImage = null;
            this.btnCheckout.onHoverState.BorderColor = System.Drawing.Color.Black;
            this.btnCheckout.onHoverState.BorderRadius = 10;
            this.btnCheckout.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCheckout.onHoverState.BorderThickness = 1;
            this.btnCheckout.onHoverState.FillColor = System.Drawing.Color.DarkBlue;
            this.btnCheckout.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnCheckout.onHoverState.IconLeftImage = null;
            this.btnCheckout.onHoverState.IconRightImage = null;
            this.btnCheckout.OnIdleState.BorderColor = System.Drawing.Color.Black;
            this.btnCheckout.OnIdleState.BorderRadius = 10;
            this.btnCheckout.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCheckout.OnIdleState.BorderThickness = 1;
            this.btnCheckout.OnIdleState.FillColor = System.Drawing.Color.White;
            this.btnCheckout.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.btnCheckout.OnIdleState.IconLeftImage = null;
            this.btnCheckout.OnIdleState.IconRightImage = null;
            this.btnCheckout.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnCheckout.OnPressedState.BorderRadius = 10;
            this.btnCheckout.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCheckout.OnPressedState.BorderThickness = 1;
            this.btnCheckout.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnCheckout.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnCheckout.OnPressedState.IconLeftImage = null;
            this.btnCheckout.OnPressedState.IconRightImage = null;
            this.btnCheckout.Size = new System.Drawing.Size(212, 29);
            this.btnCheckout.TabIndex = 23;
            this.btnCheckout.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnCheckout.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnCheckout.TextMarginLeft = 0;
            this.btnCheckout.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnCheckout.UseDefaultRadiusAndThickness = true;
            this.btnCheckout.Click += new System.EventHandler(this.btnCheckout_Click);
            // 
            // bunifuPanel1
            // 
            this.bunifuPanel1.BackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(192)))));
            this.bunifuPanel1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuPanel1.BackgroundImage")));
            this.bunifuPanel1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuPanel1.BorderColor = System.Drawing.Color.Transparent;
            this.bunifuPanel1.BorderRadius = 20;
            this.bunifuPanel1.BorderThickness = 1;
            this.bunifuPanel1.Controls.Add(this.lblChange);
            this.bunifuPanel1.Location = new System.Drawing.Point(130, 342);
            this.bunifuPanel1.Name = "bunifuPanel1";
            this.bunifuPanel1.ShowBorders = true;
            this.bunifuPanel1.Size = new System.Drawing.Size(270, 52);
            this.bunifuPanel1.TabIndex = 13;
            // 
            // bunifuPanel2
            // 
            this.bunifuPanel2.BackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(192)))));
            this.bunifuPanel2.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuPanel2.BackgroundImage")));
            this.bunifuPanel2.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuPanel2.BorderColor = System.Drawing.Color.Transparent;
            this.bunifuPanel2.BorderRadius = 20;
            this.bunifuPanel2.BorderThickness = 1;
            this.bunifuPanel2.Controls.Add(this.lblTotalAmount);
            this.bunifuPanel2.Location = new System.Drawing.Point(28, 65);
            this.bunifuPanel2.Name = "bunifuPanel2";
            this.bunifuPanel2.ShowBorders = true;
            this.bunifuPanel2.Size = new System.Drawing.Size(364, 52);
            this.bunifuPanel2.TabIndex = 22;
            // 
            // BarcodeScannerApp
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(904, 719);
            this.Controls.Add(this.btnCheckout);
            this.Controls.Add(this.pnlPayment);
            this.Controls.Add(this.panelGrandtotal);
            this.Controls.Add(this.goHome);
            this.Controls.Add(this.btnExportHistory);
            this.Controls.Add(this.btnClearHistory);
            this.Controls.Add(this.lstScanHistory);
            this.Controls.Add(this.btnStop);
            this.Controls.Add(this.bunifuLabel1);
            this.Controls.Add(this.bunifuLabel2);
            this.Controls.Add(this.btnStart);
            this.Controls.Add(this.txtInfo);
            this.Controls.Add(this.Camera);
            this.Controls.Add(this.cboCamera);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Icon = ((System.Drawing.Icon)(resources.GetObject("$this.Icon")));
            this.Name = "BarcodeScannerApp";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = " Barcode Scanner";
            this.FormClosing += new System.Windows.Forms.FormClosingEventHandler(this.Form1_FormClosing);
            this.FormClosed += new System.Windows.Forms.FormClosedEventHandler(this.Form1_FormClosed);
            this.Load += new System.EventHandler(this.Form1_Load);
            ((System.ComponentModel.ISupportInitialize)(this.Camera)).EndInit();
            this.panelGrandtotal.ResumeLayout(false);
            this.panelGrandtotal.PerformLayout();
            this.pnlPayment.ResumeLayout(false);
            this.pnlPayment.PerformLayout();
            this.bunifuPanel1.ResumeLayout(false);
            this.bunifuPanel1.PerformLayout();
            this.bunifuPanel2.ResumeLayout(false);
            this.bunifuPanel2.PerformLayout();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private System.Windows.Forms.ComboBox cboCamera;
        private Bunifu.UI.WinForms.BunifuPictureBox Camera;
        private Bunifu.UI.WinForms.BunifuTextBox txtInfo;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnStart;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel2;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnStop;
        private System.Windows.Forms.ListBox lstScanHistory;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnClearHistory;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnExportHistory;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton goHome;
        private Bunifu.UI.WinForms.BunifuPanel panelGrandtotal;
        private Bunifu.UI.WinForms.BunifuLabel txtNumber;
        private Bunifu.UI.WinForms.BunifuLabel txtTotal;
        private Bunifu.Framework.UI.BunifuElipse bunifuElipse1;
        private Bunifu.UI.WinForms.BunifuShadowPanel pnlPayment;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton bunifuButton1;
        private Bunifu.UI.WinForms.BunifuLabel lblChange;
        private Bunifu.UI.WinForms.BunifuLabel lblChangeTitle;
        private Bunifu.UI.WinForms.BunifuTextBox txtCash;
        private Bunifu.UI.WinForms.BunifuLabel lblPayTitle;
        private Bunifu.UI.WinForms.BunifuLabel lblTotalAmount;
        private Bunifu.UI.WinForms.BunifuLabel lblTotalTitle;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnCheckout;
        private Bunifu.UI.WinForms.BunifuPanel bunifuPanel1;
        private Bunifu.UI.WinForms.BunifuPanel bunifuPanel2;
    }
}

