namespace barcodescanner.Forms
{
    partial class History
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle9 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle10 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle11 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle12 = new System.Windows.Forms.DataGridViewCellStyle();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(History));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges11 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges12 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges13 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges14 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges15 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            this.dgvHistory = new Bunifu.UI.WinForms.BunifuDataGridView();
            this.bunifuLabel1 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuPanel1 = new Bunifu.UI.WinForms.BunifuPanel();
            this.btnHistory = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnCustomer = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.txtMindeus = new Bunifu.UI.WinForms.BunifuLabel();
            this.button2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnDashboard = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnOrder = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuPictureBox1 = new Bunifu.UI.WinForms.BunifuPictureBox();
            this.bunifuElipse1 = new Bunifu.Framework.UI.BunifuElipse(this.components);
            this.txtSearch = new Bunifu.UI.WinForms.BunifuTextBox();
            ((System.ComponentModel.ISupportInitialize)(this.dgvHistory)).BeginInit();
            this.bunifuPanel1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.bunifuPictureBox1)).BeginInit();
            this.SuspendLayout();
            // 
            // dgvHistory
            // 
            this.dgvHistory.AllowCustomTheming = true;
            this.dgvHistory.AllowUserToAddRows = false;
            this.dgvHistory.AllowUserToDeleteRows = false;
            this.dgvHistory.AllowUserToResizeRows = false;
            dataGridViewCellStyle9.BackColor = System.Drawing.SystemColors.Control;
            dataGridViewCellStyle9.ForeColor = System.Drawing.Color.Black;
            this.dgvHistory.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle9;
            this.dgvHistory.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.dgvHistory.BackgroundColor = System.Drawing.SystemColors.Control;
            this.dgvHistory.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.dgvHistory.CellBorderStyle = System.Windows.Forms.DataGridViewCellBorderStyle.SingleHorizontal;
            this.dgvHistory.ColumnHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
            dataGridViewCellStyle10.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle10.BackColor = System.Drawing.Color.DarkBlue;
            dataGridViewCellStyle10.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle10.ForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle10.SelectionBackColor = System.Drawing.Color.DarkBlue;
            dataGridViewCellStyle10.SelectionForeColor = System.Drawing.SystemColors.Control;
            dataGridViewCellStyle10.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.dgvHistory.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle10;
            this.dgvHistory.ColumnHeadersHeight = 40;
            this.dgvHistory.CurrentTheme.AlternatingRowsStyle.BackColor = System.Drawing.SystemColors.Control;
            this.dgvHistory.CurrentTheme.AlternatingRowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.dgvHistory.CurrentTheme.AlternatingRowsStyle.ForeColor = System.Drawing.Color.Black;
            this.dgvHistory.CurrentTheme.AlternatingRowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            this.dgvHistory.CurrentTheme.AlternatingRowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            this.dgvHistory.CurrentTheme.BackColor = System.Drawing.SystemColors.Control;
            this.dgvHistory.CurrentTheme.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.dgvHistory.CurrentTheme.HeaderStyle.BackColor = System.Drawing.Color.DarkBlue;
            this.dgvHistory.CurrentTheme.HeaderStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            this.dgvHistory.CurrentTheme.HeaderStyle.ForeColor = System.Drawing.Color.White;
            this.dgvHistory.CurrentTheme.HeaderStyle.SelectionBackColor = System.Drawing.Color.DarkBlue;
            this.dgvHistory.CurrentTheme.HeaderStyle.SelectionForeColor = System.Drawing.SystemColors.Control;
            this.dgvHistory.CurrentTheme.Name = null;
            this.dgvHistory.CurrentTheme.RowsStyle.BackColor = System.Drawing.SystemColors.Control;
            this.dgvHistory.CurrentTheme.RowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.dgvHistory.CurrentTheme.RowsStyle.ForeColor = System.Drawing.Color.Black;
            this.dgvHistory.CurrentTheme.RowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            this.dgvHistory.CurrentTheme.RowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle11.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle11.BackColor = System.Drawing.SystemColors.Control;
            dataGridViewCellStyle11.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle11.ForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle11.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle11.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle11.WrapMode = System.Windows.Forms.DataGridViewTriState.False;
            this.dgvHistory.DefaultCellStyle = dataGridViewCellStyle11;
            this.dgvHistory.EnableHeadersVisualStyles = false;
            this.dgvHistory.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.dgvHistory.HeaderBackColor = System.Drawing.Color.DarkBlue;
            this.dgvHistory.HeaderBgColor = System.Drawing.Color.Empty;
            this.dgvHistory.HeaderForeColor = System.Drawing.Color.White;
            this.dgvHistory.Location = new System.Drawing.Point(293, 72);
            this.dgvHistory.Name = "dgvHistory";
            this.dgvHistory.ReadOnly = true;
            dataGridViewCellStyle12.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle12.BackColor = System.Drawing.Color.DarkBlue;
            dataGridViewCellStyle12.Font = new System.Drawing.Font("Segoe UI", 10.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle12.ForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle12.SelectionBackColor = System.Drawing.SystemColors.Highlight;
            dataGridViewCellStyle12.SelectionForeColor = System.Drawing.SystemColors.HighlightText;
            dataGridViewCellStyle12.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.dgvHistory.RowHeadersDefaultCellStyle = dataGridViewCellStyle12;
            this.dgvHistory.RowHeadersVisible = false;
            this.dgvHistory.RowTemplate.Height = 40;
            this.dgvHistory.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.dgvHistory.Size = new System.Drawing.Size(1041, 702);
            this.dgvHistory.TabIndex = 47;
            this.dgvHistory.Theme = Bunifu.UI.WinForms.BunifuDataGridView.PresetThemes.Light;
            this.dgvHistory.CellContentClick += new System.Windows.Forms.DataGridViewCellEventHandler(this.dgvHistory_CellContentClick);
            // 
            // bunifuLabel1
            // 
            this.bunifuLabel1.AllowParentOverrides = false;
            this.bunifuLabel1.AutoEllipsis = false;
            this.bunifuLabel1.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.Font = new System.Drawing.Font("Gadugi", 26.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel1.ForeColor = System.Drawing.Color.Black;
            this.bunifuLabel1.Location = new System.Drawing.Point(293, 25);
            this.bunifuLabel1.Name = "bunifuLabel1";
            this.bunifuLabel1.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel1.Size = new System.Drawing.Size(150, 41);
            this.bunifuLabel1.TabIndex = 16;
            this.bunifuLabel1.Text = "HISTORY";
            this.bunifuLabel1.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel1.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuPanel1
            // 
            this.bunifuPanel1.BackgroundColor = System.Drawing.SystemColors.Control;
            this.bunifuPanel1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuPanel1.BackgroundImage")));
            this.bunifuPanel1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuPanel1.BorderColor = System.Drawing.Color.DarkGray;
            this.bunifuPanel1.BorderRadius = 3;
            this.bunifuPanel1.BorderThickness = 1;
            this.bunifuPanel1.Controls.Add(this.btnHistory);
            this.bunifuPanel1.Controls.Add(this.btnCustomer);
            this.bunifuPanel1.Controls.Add(this.txtMindeus);
            this.bunifuPanel1.Controls.Add(this.button2);
            this.bunifuPanel1.Controls.Add(this.btnDashboard);
            this.bunifuPanel1.Controls.Add(this.btnOrder);
            this.bunifuPanel1.Controls.Add(this.bunifuPictureBox1);
            this.bunifuPanel1.Dock = System.Windows.Forms.DockStyle.Left;
            this.bunifuPanel1.Location = new System.Drawing.Point(0, 0);
            this.bunifuPanel1.Name = "bunifuPanel1";
            this.bunifuPanel1.ShowBorders = true;
            this.bunifuPanel1.Size = new System.Drawing.Size(249, 814);
            this.bunifuPanel1.TabIndex = 46;
            // 
            // btnHistory
            // 
            this.btnHistory.AllowAnimations = true;
            this.btnHistory.AllowMouseEffects = true;
            this.btnHistory.AllowToggling = false;
            this.btnHistory.AnimationSpeed = 200;
            this.btnHistory.AutoGenerateColors = false;
            this.btnHistory.AutoRoundBorders = false;
            this.btnHistory.AutoSizeLeftIcon = true;
            this.btnHistory.AutoSizeRightIcon = true;
            this.btnHistory.BackColor = System.Drawing.Color.Transparent;
            this.btnHistory.BackColor1 = System.Drawing.Color.DarkBlue;
            this.btnHistory.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnHistory.BackgroundImage")));
            this.btnHistory.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnHistory.ButtonText = "Order History";
            this.btnHistory.ButtonTextMarginLeft = 0;
            this.btnHistory.ColorContrastOnClick = 45;
            this.btnHistory.ColorContrastOnHover = 45;
            this.btnHistory.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges11.BottomLeft = true;
            borderEdges11.BottomRight = true;
            borderEdges11.TopLeft = true;
            borderEdges11.TopRight = true;
            this.btnHistory.CustomizableEdges = borderEdges11;
            this.btnHistory.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnHistory.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnHistory.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnHistory.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnHistory.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnHistory.Font = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnHistory.ForeColor = System.Drawing.Color.White;
            this.btnHistory.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnHistory.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnHistory.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnHistory.IconMarginLeft = 11;
            this.btnHistory.IconPadding = 10;
            this.btnHistory.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnHistory.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnHistory.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnHistory.IconSize = 25;
            this.btnHistory.IdleBorderColor = System.Drawing.SystemColors.Control;
            this.btnHistory.IdleBorderRadius = 18;
            this.btnHistory.IdleBorderThickness = 1;
            this.btnHistory.IdleFillColor = System.Drawing.Color.DarkBlue;
            this.btnHistory.IdleIconLeftImage = null;
            this.btnHistory.IdleIconRightImage = null;
            this.btnHistory.IndicateFocus = false;
            this.btnHistory.Location = new System.Drawing.Point(21, 327);
            this.btnHistory.Name = "btnHistory";
            this.btnHistory.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnHistory.OnDisabledState.BorderRadius = 18;
            this.btnHistory.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnHistory.OnDisabledState.BorderThickness = 1;
            this.btnHistory.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnHistory.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnHistory.OnDisabledState.IconLeftImage = null;
            this.btnHistory.OnDisabledState.IconRightImage = null;
            this.btnHistory.onHoverState.BorderColor = System.Drawing.SystemColors.Control;
            this.btnHistory.onHoverState.BorderRadius = 18;
            this.btnHistory.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnHistory.onHoverState.BorderThickness = 1;
            this.btnHistory.onHoverState.FillColor = System.Drawing.Color.DarkBlue;
            this.btnHistory.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnHistory.onHoverState.IconLeftImage = null;
            this.btnHistory.onHoverState.IconRightImage = null;
            this.btnHistory.OnIdleState.BorderColor = System.Drawing.SystemColors.Control;
            this.btnHistory.OnIdleState.BorderRadius = 18;
            this.btnHistory.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnHistory.OnIdleState.BorderThickness = 1;
            this.btnHistory.OnIdleState.FillColor = System.Drawing.Color.DarkBlue;
            this.btnHistory.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnHistory.OnIdleState.IconLeftImage = null;
            this.btnHistory.OnIdleState.IconRightImage = null;
            this.btnHistory.OnPressedState.BorderColor = System.Drawing.SystemColors.Control;
            this.btnHistory.OnPressedState.BorderRadius = 18;
            this.btnHistory.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnHistory.OnPressedState.BorderThickness = 1;
            this.btnHistory.OnPressedState.FillColor = System.Drawing.Color.DarkBlue;
            this.btnHistory.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnHistory.OnPressedState.IconLeftImage = null;
            this.btnHistory.OnPressedState.IconRightImage = null;
            this.btnHistory.Size = new System.Drawing.Size(197, 39);
            this.btnHistory.TabIndex = 15;
            this.btnHistory.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnHistory.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnHistory.TextMarginLeft = 0;
            this.btnHistory.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnHistory.UseDefaultRadiusAndThickness = true;
            // 
            // btnCustomer
            // 
            this.btnCustomer.AllowAnimations = true;
            this.btnCustomer.AllowMouseEffects = true;
            this.btnCustomer.AllowToggling = false;
            this.btnCustomer.AnimationSpeed = 200;
            this.btnCustomer.AutoGenerateColors = false;
            this.btnCustomer.AutoRoundBorders = false;
            this.btnCustomer.AutoSizeLeftIcon = true;
            this.btnCustomer.AutoSizeRightIcon = true;
            this.btnCustomer.BackColor = System.Drawing.Color.Transparent;
            this.btnCustomer.BackColor1 = System.Drawing.SystemColors.Control;
            this.btnCustomer.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnCustomer.BackgroundImage")));
            this.btnCustomer.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCustomer.ButtonText = "Customer";
            this.btnCustomer.ButtonTextMarginLeft = 0;
            this.btnCustomer.ColorContrastOnClick = 45;
            this.btnCustomer.ColorContrastOnHover = 45;
            this.btnCustomer.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges12.BottomLeft = true;
            borderEdges12.BottomRight = true;
            borderEdges12.TopLeft = true;
            borderEdges12.TopRight = true;
            this.btnCustomer.CustomizableEdges = borderEdges12;
            this.btnCustomer.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnCustomer.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnCustomer.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnCustomer.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnCustomer.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnCustomer.Font = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnCustomer.ForeColor = System.Drawing.Color.Black;
            this.btnCustomer.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnCustomer.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnCustomer.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnCustomer.IconMarginLeft = 11;
            this.btnCustomer.IconPadding = 10;
            this.btnCustomer.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnCustomer.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnCustomer.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnCustomer.IconSize = 25;
            this.btnCustomer.IdleBorderColor = System.Drawing.SystemColors.Control;
            this.btnCustomer.IdleBorderRadius = 18;
            this.btnCustomer.IdleBorderThickness = 1;
            this.btnCustomer.IdleFillColor = System.Drawing.SystemColors.Control;
            this.btnCustomer.IdleIconLeftImage = null;
            this.btnCustomer.IdleIconRightImage = null;
            this.btnCustomer.IndicateFocus = false;
            this.btnCustomer.Location = new System.Drawing.Point(21, 271);
            this.btnCustomer.Name = "btnCustomer";
            this.btnCustomer.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnCustomer.OnDisabledState.BorderRadius = 18;
            this.btnCustomer.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCustomer.OnDisabledState.BorderThickness = 1;
            this.btnCustomer.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnCustomer.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnCustomer.OnDisabledState.IconLeftImage = null;
            this.btnCustomer.OnDisabledState.IconRightImage = null;
            this.btnCustomer.onHoverState.BorderColor = System.Drawing.SystemColors.Control;
            this.btnCustomer.onHoverState.BorderRadius = 18;
            this.btnCustomer.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCustomer.onHoverState.BorderThickness = 1;
            this.btnCustomer.onHoverState.FillColor = System.Drawing.Color.Gray;
            this.btnCustomer.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.btnCustomer.onHoverState.IconLeftImage = null;
            this.btnCustomer.onHoverState.IconRightImage = null;
            this.btnCustomer.OnIdleState.BorderColor = System.Drawing.SystemColors.Control;
            this.btnCustomer.OnIdleState.BorderRadius = 18;
            this.btnCustomer.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCustomer.OnIdleState.BorderThickness = 1;
            this.btnCustomer.OnIdleState.FillColor = System.Drawing.SystemColors.Control;
            this.btnCustomer.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.btnCustomer.OnIdleState.IconLeftImage = null;
            this.btnCustomer.OnIdleState.IconRightImage = null;
            this.btnCustomer.OnPressedState.BorderColor = System.Drawing.SystemColors.Control;
            this.btnCustomer.OnPressedState.BorderRadius = 18;
            this.btnCustomer.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCustomer.OnPressedState.BorderThickness = 1;
            this.btnCustomer.OnPressedState.FillColor = System.Drawing.Color.DarkBlue;
            this.btnCustomer.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnCustomer.OnPressedState.IconLeftImage = null;
            this.btnCustomer.OnPressedState.IconRightImage = null;
            this.btnCustomer.Size = new System.Drawing.Size(197, 39);
            this.btnCustomer.TabIndex = 14;
            this.btnCustomer.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnCustomer.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnCustomer.TextMarginLeft = 0;
            this.btnCustomer.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnCustomer.UseDefaultRadiusAndThickness = true;
            this.btnCustomer.Click += new System.EventHandler(this.btnCustomer_Click);
            // 
            // txtMindeus
            // 
            this.txtMindeus.AllowParentOverrides = false;
            this.txtMindeus.AutoEllipsis = false;
            this.txtMindeus.Cursor = System.Windows.Forms.Cursors.Default;
            this.txtMindeus.CursorType = System.Windows.Forms.Cursors.Default;
            this.txtMindeus.Font = new System.Drawing.Font("Gadugi", 26.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtMindeus.ForeColor = System.Drawing.Color.DarkBlue;
            this.txtMindeus.Location = new System.Drawing.Point(44, 41);
            this.txtMindeus.Name = "txtMindeus";
            this.txtMindeus.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.txtMindeus.Size = new System.Drawing.Size(163, 41);
            this.txtMindeus.TabIndex = 12;
            this.txtMindeus.Text = "MINDEUS";
            this.txtMindeus.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.txtMindeus.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // button2
            // 
            this.button2.AllowAnimations = true;
            this.button2.AllowMouseEffects = true;
            this.button2.AllowToggling = false;
            this.button2.AnimationSpeed = 200;
            this.button2.AutoGenerateColors = false;
            this.button2.AutoRoundBorders = false;
            this.button2.AutoSizeLeftIcon = true;
            this.button2.AutoSizeRightIcon = true;
            this.button2.BackColor = System.Drawing.Color.Transparent;
            this.button2.BackColor1 = System.Drawing.SystemColors.Control;
            this.button2.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("button2.BackgroundImage")));
            this.button2.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.button2.ButtonText = "Exit";
            this.button2.ButtonTextMarginLeft = 0;
            this.button2.ColorContrastOnClick = 45;
            this.button2.ColorContrastOnHover = 45;
            this.button2.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges13.BottomLeft = true;
            borderEdges13.BottomRight = true;
            borderEdges13.TopLeft = true;
            borderEdges13.TopRight = true;
            this.button2.CustomizableEdges = borderEdges13;
            this.button2.DialogResult = System.Windows.Forms.DialogResult.None;
            this.button2.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.button2.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.button2.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.button2.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.button2.Font = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.button2.ForeColor = System.Drawing.Color.Black;
            this.button2.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.button2.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.button2.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.button2.IconMarginLeft = 11;
            this.button2.IconPadding = 10;
            this.button2.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.button2.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.button2.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.button2.IconSize = 25;
            this.button2.IdleBorderColor = System.Drawing.SystemColors.Control;
            this.button2.IdleBorderRadius = 18;
            this.button2.IdleBorderThickness = 1;
            this.button2.IdleFillColor = System.Drawing.SystemColors.Control;
            this.button2.IdleIconLeftImage = null;
            this.button2.IdleIconRightImage = null;
            this.button2.IndicateFocus = false;
            this.button2.Location = new System.Drawing.Point(21, 753);
            this.button2.Name = "button2";
            this.button2.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.button2.OnDisabledState.BorderRadius = 18;
            this.button2.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.button2.OnDisabledState.BorderThickness = 1;
            this.button2.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.button2.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.button2.OnDisabledState.IconLeftImage = null;
            this.button2.OnDisabledState.IconRightImage = null;
            this.button2.onHoverState.BorderColor = System.Drawing.SystemColors.Control;
            this.button2.onHoverState.BorderRadius = 18;
            this.button2.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.button2.onHoverState.BorderThickness = 1;
            this.button2.onHoverState.FillColor = System.Drawing.Color.DarkBlue;
            this.button2.onHoverState.ForeColor = System.Drawing.Color.White;
            this.button2.onHoverState.IconLeftImage = null;
            this.button2.onHoverState.IconRightImage = null;
            this.button2.OnIdleState.BorderColor = System.Drawing.SystemColors.Control;
            this.button2.OnIdleState.BorderRadius = 18;
            this.button2.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.button2.OnIdleState.BorderThickness = 1;
            this.button2.OnIdleState.FillColor = System.Drawing.SystemColors.Control;
            this.button2.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.button2.OnIdleState.IconLeftImage = null;
            this.button2.OnIdleState.IconRightImage = null;
            this.button2.OnPressedState.BorderColor = System.Drawing.SystemColors.Control;
            this.button2.OnPressedState.BorderRadius = 18;
            this.button2.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.button2.OnPressedState.BorderThickness = 1;
            this.button2.OnPressedState.FillColor = System.Drawing.Color.DarkBlue;
            this.button2.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.button2.OnPressedState.IconLeftImage = null;
            this.button2.OnPressedState.IconRightImage = null;
            this.button2.Size = new System.Drawing.Size(197, 39);
            this.button2.TabIndex = 8;
            this.button2.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.button2.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.button2.TextMarginLeft = 0;
            this.button2.TextPadding = new System.Windows.Forms.Padding(0);
            this.button2.UseDefaultRadiusAndThickness = true;
            this.button2.Click += new System.EventHandler(this.button2_Click);
            // 
            // btnDashboard
            // 
            this.btnDashboard.AllowAnimations = true;
            this.btnDashboard.AllowMouseEffects = true;
            this.btnDashboard.AllowToggling = false;
            this.btnDashboard.AnimationSpeed = 200;
            this.btnDashboard.AutoGenerateColors = false;
            this.btnDashboard.AutoRoundBorders = false;
            this.btnDashboard.AutoSizeLeftIcon = true;
            this.btnDashboard.AutoSizeRightIcon = true;
            this.btnDashboard.BackColor = System.Drawing.Color.Transparent;
            this.btnDashboard.BackColor1 = System.Drawing.SystemColors.Control;
            this.btnDashboard.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnDashboard.BackgroundImage")));
            this.btnDashboard.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnDashboard.ButtonText = "Dashboard";
            this.btnDashboard.ButtonTextMarginLeft = 0;
            this.btnDashboard.ColorContrastOnClick = 45;
            this.btnDashboard.ColorContrastOnHover = 45;
            this.btnDashboard.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges14.BottomLeft = true;
            borderEdges14.BottomRight = true;
            borderEdges14.TopLeft = true;
            borderEdges14.TopRight = true;
            this.btnDashboard.CustomizableEdges = borderEdges14;
            this.btnDashboard.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnDashboard.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnDashboard.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnDashboard.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnDashboard.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnDashboard.Font = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnDashboard.ForeColor = System.Drawing.Color.Black;
            this.btnDashboard.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnDashboard.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnDashboard.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnDashboard.IconMarginLeft = 11;
            this.btnDashboard.IconPadding = 10;
            this.btnDashboard.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnDashboard.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnDashboard.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnDashboard.IconSize = 25;
            this.btnDashboard.IdleBorderColor = System.Drawing.SystemColors.Control;
            this.btnDashboard.IdleBorderRadius = 18;
            this.btnDashboard.IdleBorderThickness = 1;
            this.btnDashboard.IdleFillColor = System.Drawing.SystemColors.Control;
            this.btnDashboard.IdleIconLeftImage = null;
            this.btnDashboard.IdleIconRightImage = null;
            this.btnDashboard.IndicateFocus = false;
            this.btnDashboard.Location = new System.Drawing.Point(21, 155);
            this.btnDashboard.Name = "btnDashboard";
            this.btnDashboard.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnDashboard.OnDisabledState.BorderRadius = 18;
            this.btnDashboard.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnDashboard.OnDisabledState.BorderThickness = 1;
            this.btnDashboard.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnDashboard.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnDashboard.OnDisabledState.IconLeftImage = null;
            this.btnDashboard.OnDisabledState.IconRightImage = null;
            this.btnDashboard.onHoverState.BorderColor = System.Drawing.SystemColors.Control;
            this.btnDashboard.onHoverState.BorderRadius = 18;
            this.btnDashboard.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnDashboard.onHoverState.BorderThickness = 1;
            this.btnDashboard.onHoverState.FillColor = System.Drawing.Color.Gray;
            this.btnDashboard.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.btnDashboard.onHoverState.IconLeftImage = null;
            this.btnDashboard.onHoverState.IconRightImage = null;
            this.btnDashboard.OnIdleState.BorderColor = System.Drawing.SystemColors.Control;
            this.btnDashboard.OnIdleState.BorderRadius = 18;
            this.btnDashboard.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnDashboard.OnIdleState.BorderThickness = 1;
            this.btnDashboard.OnIdleState.FillColor = System.Drawing.SystemColors.Control;
            this.btnDashboard.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.btnDashboard.OnIdleState.IconLeftImage = null;
            this.btnDashboard.OnIdleState.IconRightImage = null;
            this.btnDashboard.OnPressedState.BorderColor = System.Drawing.SystemColors.Control;
            this.btnDashboard.OnPressedState.BorderRadius = 18;
            this.btnDashboard.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnDashboard.OnPressedState.BorderThickness = 1;
            this.btnDashboard.OnPressedState.FillColor = System.Drawing.Color.DarkBlue;
            this.btnDashboard.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnDashboard.OnPressedState.IconLeftImage = null;
            this.btnDashboard.OnPressedState.IconRightImage = null;
            this.btnDashboard.Size = new System.Drawing.Size(197, 39);
            this.btnDashboard.TabIndex = 6;
            this.btnDashboard.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnDashboard.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnDashboard.TextMarginLeft = 0;
            this.btnDashboard.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnDashboard.UseDefaultRadiusAndThickness = true;
            this.btnDashboard.Click += new System.EventHandler(this.btnDashboard_Click);
            // 
            // btnOrder
            // 
            this.btnOrder.AllowAnimations = true;
            this.btnOrder.AllowMouseEffects = true;
            this.btnOrder.AllowToggling = false;
            this.btnOrder.AnimationSpeed = 200;
            this.btnOrder.AutoGenerateColors = false;
            this.btnOrder.AutoRoundBorders = false;
            this.btnOrder.AutoSizeLeftIcon = true;
            this.btnOrder.AutoSizeRightIcon = true;
            this.btnOrder.BackColor = System.Drawing.Color.Transparent;
            this.btnOrder.BackColor1 = System.Drawing.SystemColors.Control;
            this.btnOrder.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnOrder.BackgroundImage")));
            this.btnOrder.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnOrder.ButtonText = "Orders";
            this.btnOrder.ButtonTextMarginLeft = 0;
            this.btnOrder.ColorContrastOnClick = 45;
            this.btnOrder.ColorContrastOnHover = 45;
            this.btnOrder.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges15.BottomLeft = true;
            borderEdges15.BottomRight = true;
            borderEdges15.TopLeft = true;
            borderEdges15.TopRight = true;
            this.btnOrder.CustomizableEdges = borderEdges15;
            this.btnOrder.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnOrder.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnOrder.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnOrder.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnOrder.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnOrder.Font = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnOrder.ForeColor = System.Drawing.Color.Black;
            this.btnOrder.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnOrder.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnOrder.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnOrder.IconMarginLeft = 11;
            this.btnOrder.IconPadding = 10;
            this.btnOrder.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnOrder.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnOrder.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnOrder.IconSize = 25;
            this.btnOrder.IdleBorderColor = System.Drawing.SystemColors.Control;
            this.btnOrder.IdleBorderRadius = 18;
            this.btnOrder.IdleBorderThickness = 1;
            this.btnOrder.IdleFillColor = System.Drawing.SystemColors.Control;
            this.btnOrder.IdleIconLeftImage = null;
            this.btnOrder.IdleIconRightImage = null;
            this.btnOrder.IndicateFocus = false;
            this.btnOrder.Location = new System.Drawing.Point(21, 214);
            this.btnOrder.Name = "btnOrder";
            this.btnOrder.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnOrder.OnDisabledState.BorderRadius = 18;
            this.btnOrder.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnOrder.OnDisabledState.BorderThickness = 1;
            this.btnOrder.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnOrder.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnOrder.OnDisabledState.IconLeftImage = null;
            this.btnOrder.OnDisabledState.IconRightImage = null;
            this.btnOrder.onHoverState.BorderColor = System.Drawing.SystemColors.Control;
            this.btnOrder.onHoverState.BorderRadius = 18;
            this.btnOrder.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnOrder.onHoverState.BorderThickness = 1;
            this.btnOrder.onHoverState.FillColor = System.Drawing.Color.Gray;
            this.btnOrder.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.btnOrder.onHoverState.IconLeftImage = null;
            this.btnOrder.onHoverState.IconRightImage = null;
            this.btnOrder.OnIdleState.BorderColor = System.Drawing.SystemColors.Control;
            this.btnOrder.OnIdleState.BorderRadius = 18;
            this.btnOrder.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnOrder.OnIdleState.BorderThickness = 1;
            this.btnOrder.OnIdleState.FillColor = System.Drawing.SystemColors.Control;
            this.btnOrder.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.btnOrder.OnIdleState.IconLeftImage = null;
            this.btnOrder.OnIdleState.IconRightImage = null;
            this.btnOrder.OnPressedState.BorderColor = System.Drawing.SystemColors.Control;
            this.btnOrder.OnPressedState.BorderRadius = 18;
            this.btnOrder.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnOrder.OnPressedState.BorderThickness = 1;
            this.btnOrder.OnPressedState.FillColor = System.Drawing.SystemColors.Control;
            this.btnOrder.OnPressedState.ForeColor = System.Drawing.Color.Black;
            this.btnOrder.OnPressedState.IconLeftImage = null;
            this.btnOrder.OnPressedState.IconRightImage = null;
            this.btnOrder.Size = new System.Drawing.Size(197, 39);
            this.btnOrder.TabIndex = 5;
            this.btnOrder.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnOrder.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnOrder.TextMarginLeft = 0;
            this.btnOrder.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnOrder.UseDefaultRadiusAndThickness = true;
            this.btnOrder.Click += new System.EventHandler(this.btnOrder_Click);
            // 
            // bunifuPictureBox1
            // 
            this.bunifuPictureBox1.AllowFocused = false;
            this.bunifuPictureBox1.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.bunifuPictureBox1.AutoSizeHeight = false;
            this.bunifuPictureBox1.BorderRadius = 0;
            this.bunifuPictureBox1.Image = global::barcodescanner.Properties.Resources.linya;
            this.bunifuPictureBox1.IsCircle = true;
            this.bunifuPictureBox1.Location = new System.Drawing.Point(44, 664);
            this.bunifuPictureBox1.Name = "bunifuPictureBox1";
            this.bunifuPictureBox1.Size = new System.Drawing.Size(150, 150);
            this.bunifuPictureBox1.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.bunifuPictureBox1.TabIndex = 4;
            this.bunifuPictureBox1.TabStop = false;
            this.bunifuPictureBox1.Type = Bunifu.UI.WinForms.BunifuPictureBox.Types.Square;
            // 
            // bunifuElipse1
            // 
            this.bunifuElipse1.ElipseRadius = 50;
            this.bunifuElipse1.TargetControl = this;
            // 
            // txtSearch
            // 
            this.txtSearch.AcceptsReturn = false;
            this.txtSearch.AcceptsTab = false;
            this.txtSearch.AnimationSpeed = 200;
            this.txtSearch.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtSearch.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtSearch.BackColor = System.Drawing.Color.Transparent;
            this.txtSearch.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtSearch.BackgroundImage")));
            this.txtSearch.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtSearch.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtSearch.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtSearch.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtSearch.BorderRadius = 20;
            this.txtSearch.BorderThickness = 1;
            this.txtSearch.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtSearch.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtSearch.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtSearch.DefaultText = "";
            this.txtSearch.FillColor = System.Drawing.Color.White;
            this.txtSearch.HideSelection = true;
            this.txtSearch.IconLeft = null;
            this.txtSearch.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtSearch.IconPadding = 10;
            this.txtSearch.IconRight = null;
            this.txtSearch.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtSearch.Lines = new string[0];
            this.txtSearch.Location = new System.Drawing.Point(522, 29);
            this.txtSearch.MaxLength = 32767;
            this.txtSearch.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtSearch.Modified = false;
            this.txtSearch.Multiline = false;
            this.txtSearch.Name = "txtSearch";
            stateProperties9.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtSearch.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtSearch.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtSearch.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Silver;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Empty;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtSearch.OnIdleState = stateProperties12;
            this.txtSearch.Padding = new System.Windows.Forms.Padding(3);
            this.txtSearch.PasswordChar = '\0';
            this.txtSearch.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtSearch.PlaceholderText = "Search ";
            this.txtSearch.ReadOnly = false;
            this.txtSearch.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtSearch.SelectedText = "";
            this.txtSearch.SelectionLength = 0;
            this.txtSearch.SelectionStart = 0;
            this.txtSearch.ShortcutsEnabled = true;
            this.txtSearch.Size = new System.Drawing.Size(450, 37);
            this.txtSearch.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtSearch.TabIndex = 48;
            this.txtSearch.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtSearch.TextMarginBottom = 0;
            this.txtSearch.TextMarginLeft = 3;
            this.txtSearch.TextMarginTop = 0;
            this.txtSearch.TextPlaceholder = "Search ";
            this.txtSearch.UseSystemPasswordChar = false;
            this.txtSearch.WordWrap = true;
            this.txtSearch.TextChanged += new System.EventHandler(this.txtSearch_TextChanged);
            // 
            // History
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(1382, 814);
            this.Controls.Add(this.txtSearch);
            this.Controls.Add(this.bunifuLabel1);
            this.Controls.Add(this.dgvHistory);
            this.Controls.Add(this.bunifuPanel1);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Icon = ((System.Drawing.Icon)(resources.GetObject("$this.Icon")));
            this.Name = "History";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "History";
            this.Load += new System.EventHandler(this.History_Load);
            ((System.ComponentModel.ISupportInitialize)(this.dgvHistory)).EndInit();
            this.bunifuPanel1.ResumeLayout(false);
            this.bunifuPanel1.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.bunifuPictureBox1)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private Bunifu.UI.WinForms.BunifuPanel bunifuPanel1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnHistory;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnCustomer;
        private Bunifu.UI.WinForms.BunifuLabel txtMindeus;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton button2;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnDashboard;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnOrder;
        private Bunifu.UI.WinForms.BunifuPictureBox bunifuPictureBox1;
        private Bunifu.UI.WinForms.BunifuDataGridView dgvHistory;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel1;
        private Bunifu.Framework.UI.BunifuElipse bunifuElipse1;
        private Bunifu.UI.WinForms.BunifuTextBox txtSearch;
    }
}