namespace barcodescanner.Forms
{
    partial class Order
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Order));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges9 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges10 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges11 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges12 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges13 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges14 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle4 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle5 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle6 = new System.Windows.Forms.DataGridViewCellStyle();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges15 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges16 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            this.bunifuPanel1 = new Bunifu.UI.WinForms.BunifuPanel();
            this.btnHistory = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnDashboard = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.txtMindeus = new Bunifu.UI.WinForms.BunifuLabel();
            this.button2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnCustomer = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnOrder = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuPictureBox1 = new Bunifu.UI.WinForms.BunifuPictureBox();
            this.btnPrint = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.Items = new Bunifu.UI.WinForms.BunifuDataGridView();
            this.cboCategory = new Bunifu.UI.WinForms.BunifuDropdown();
            this.flowLayoutPanel1 = new System.Windows.Forms.FlowLayoutPanel();
            this.txtProductName = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuButton1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.panel = new System.Windows.Forms.FlowLayoutPanel();
            this.bunifuShadowPanel1 = new Bunifu.UI.WinForms.BunifuShadowPanel();
            this.picture = new Bunifu.UI.WinForms.BunifuPictureBox();
            this.txtPrice = new Bunifu.UI.WinForms.BunifuLabel();
            this.btnClear = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.cboCustomer = new Bunifu.UI.WinForms.BunifuDropdown();
            this.bunifuDatePicker1 = new Bunifu.UI.WinForms.BunifuDatePicker();
            this.bunifuPanel2 = new Bunifu.UI.WinForms.BunifuPanel();
            this.txtTotal = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel1 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuElipse1 = new Bunifu.Framework.UI.BunifuElipse(this.components);
            this.bunifuPanel1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.bunifuPictureBox1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.Items)).BeginInit();
            this.panel.SuspendLayout();
            this.bunifuShadowPanel1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.picture)).BeginInit();
            this.bunifuPanel2.SuspendLayout();
            this.SuspendLayout();
            // 
            // bunifuPanel1
            // 
            this.bunifuPanel1.BackgroundColor = System.Drawing.SystemColors.Control;
            this.bunifuPanel1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuPanel1.BackgroundImage")));
            this.bunifuPanel1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuPanel1.BorderColor = System.Drawing.Color.DarkGray;
            this.bunifuPanel1.BorderRadius = 3;
            this.bunifuPanel1.BorderThickness = 1;
            this.bunifuPanel1.Controls.Add(this.btnHistory);
            this.bunifuPanel1.Controls.Add(this.btnDashboard);
            this.bunifuPanel1.Controls.Add(this.txtMindeus);
            this.bunifuPanel1.Controls.Add(this.button2);
            this.bunifuPanel1.Controls.Add(this.btnCustomer);
            this.bunifuPanel1.Controls.Add(this.btnOrder);
            this.bunifuPanel1.Controls.Add(this.bunifuPictureBox1);
            this.bunifuPanel1.Dock = System.Windows.Forms.DockStyle.Left;
            this.bunifuPanel1.Location = new System.Drawing.Point(0, 0);
            this.bunifuPanel1.Name = "bunifuPanel1";
            this.bunifuPanel1.ShowBorders = true;
            this.bunifuPanel1.Size = new System.Drawing.Size(249, 814);
            this.bunifuPanel1.TabIndex = 47;
            // 
            // btnHistory
            // 
            this.btnHistory.AllowAnimations = true;
            this.btnHistory.AllowMouseEffects = true;
            this.btnHistory.AllowToggling = false;
            this.btnHistory.AnimationSpeed = 200;
            this.btnHistory.AutoGenerateColors = false;
            this.btnHistory.AutoRoundBorders = false;
            this.btnHistory.AutoSizeLeftIcon = true;
            this.btnHistory.AutoSizeRightIcon = true;
            this.btnHistory.BackColor = System.Drawing.Color.Transparent;
            this.btnHistory.BackColor1 = System.Drawing.SystemColors.Control;
            this.btnHistory.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnHistory.BackgroundImage")));
            this.btnHistory.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnHistory.ButtonText = "Order History";
            this.btnHistory.ButtonTextMarginLeft = 0;
            this.btnHistory.ColorContrastOnClick = 45;
            this.btnHistory.ColorContrastOnHover = 45;
            this.btnHistory.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges9.BottomLeft = true;
            borderEdges9.BottomRight = true;
            borderEdges9.TopLeft = true;
            borderEdges9.TopRight = true;
            this.btnHistory.CustomizableEdges = borderEdges9;
            this.btnHistory.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnHistory.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnHistory.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnHistory.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnHistory.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnHistory.Font = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnHistory.ForeColor = System.Drawing.Color.Black;
            this.btnHistory.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnHistory.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnHistory.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnHistory.IconMarginLeft = 11;
            this.btnHistory.IconPadding = 10;
            this.btnHistory.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnHistory.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnHistory.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnHistory.IconSize = 25;
            this.btnHistory.IdleBorderColor = System.Drawing.SystemColors.Control;
            this.btnHistory.IdleBorderRadius = 18;
            this.btnHistory.IdleBorderThickness = 1;
            this.btnHistory.IdleFillColor = System.Drawing.SystemColors.Control;
            this.btnHistory.IdleIconLeftImage = null;
            this.btnHistory.IdleIconRightImage = null;
            this.btnHistory.IndicateFocus = false;
            this.btnHistory.Location = new System.Drawing.Point(21, 327);
            this.btnHistory.Name = "btnHistory";
            this.btnHistory.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnHistory.OnDisabledState.BorderRadius = 18;
            this.btnHistory.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnHistory.OnDisabledState.BorderThickness = 1;
            this.btnHistory.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnHistory.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnHistory.OnDisabledState.IconLeftImage = null;
            this.btnHistory.OnDisabledState.IconRightImage = null;
            this.btnHistory.onHoverState.BorderColor = System.Drawing.SystemColors.Control;
            this.btnHistory.onHoverState.BorderRadius = 18;
            this.btnHistory.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnHistory.onHoverState.BorderThickness = 1;
            this.btnHistory.onHoverState.FillColor = System.Drawing.Color.Gray;
            this.btnHistory.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.btnHistory.onHoverState.IconLeftImage = null;
            this.btnHistory.onHoverState.IconRightImage = null;
            this.btnHistory.OnIdleState.BorderColor = System.Drawing.SystemColors.Control;
            this.btnHistory.OnIdleState.BorderRadius = 18;
            this.btnHistory.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnHistory.OnIdleState.BorderThickness = 1;
            this.btnHistory.OnIdleState.FillColor = System.Drawing.SystemColors.Control;
            this.btnHistory.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.btnHistory.OnIdleState.IconLeftImage = null;
            this.btnHistory.OnIdleState.IconRightImage = null;
            this.btnHistory.OnPressedState.BorderColor = System.Drawing.SystemColors.Control;
            this.btnHistory.OnPressedState.BorderRadius = 18;
            this.btnHistory.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnHistory.OnPressedState.BorderThickness = 1;
            this.btnHistory.OnPressedState.FillColor = System.Drawing.Color.DarkBlue;
            this.btnHistory.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnHistory.OnPressedState.IconLeftImage = null;
            this.btnHistory.OnPressedState.IconRightImage = null;
            this.btnHistory.Size = new System.Drawing.Size(197, 39);
            this.btnHistory.TabIndex = 16;
            this.btnHistory.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnHistory.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnHistory.TextMarginLeft = 0;
            this.btnHistory.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnHistory.UseDefaultRadiusAndThickness = true;
            this.btnHistory.Click += new System.EventHandler(this.btnHistory_Click);
            // 
            // btnDashboard
            // 
            this.btnDashboard.AllowAnimations = true;
            this.btnDashboard.AllowMouseEffects = true;
            this.btnDashboard.AllowToggling = false;
            this.btnDashboard.AnimationSpeed = 200;
            this.btnDashboard.AutoGenerateColors = false;
            this.btnDashboard.AutoRoundBorders = false;
            this.btnDashboard.AutoSizeLeftIcon = true;
            this.btnDashboard.AutoSizeRightIcon = true;
            this.btnDashboard.BackColor = System.Drawing.Color.Transparent;
            this.btnDashboard.BackColor1 = System.Drawing.SystemColors.Control;
            this.btnDashboard.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnDashboard.BackgroundImage")));
            this.btnDashboard.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnDashboard.ButtonText = "Dashboard";
            this.btnDashboard.ButtonTextMarginLeft = 0;
            this.btnDashboard.ColorContrastOnClick = 45;
            this.btnDashboard.ColorContrastOnHover = 45;
            this.btnDashboard.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges10.BottomLeft = true;
            borderEdges10.BottomRight = true;
            borderEdges10.TopLeft = true;
            borderEdges10.TopRight = true;
            this.btnDashboard.CustomizableEdges = borderEdges10;
            this.btnDashboard.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnDashboard.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnDashboard.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnDashboard.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnDashboard.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnDashboard.Font = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnDashboard.ForeColor = System.Drawing.Color.Black;
            this.btnDashboard.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnDashboard.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnDashboard.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnDashboard.IconMarginLeft = 11;
            this.btnDashboard.IconPadding = 10;
            this.btnDashboard.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnDashboard.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnDashboard.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnDashboard.IconSize = 25;
            this.btnDashboard.IdleBorderColor = System.Drawing.SystemColors.Control;
            this.btnDashboard.IdleBorderRadius = 18;
            this.btnDashboard.IdleBorderThickness = 1;
            this.btnDashboard.IdleFillColor = System.Drawing.SystemColors.Control;
            this.btnDashboard.IdleIconLeftImage = null;
            this.btnDashboard.IdleIconRightImage = null;
            this.btnDashboard.IndicateFocus = false;
            this.btnDashboard.Location = new System.Drawing.Point(21, 155);
            this.btnDashboard.Name = "btnDashboard";
            this.btnDashboard.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnDashboard.OnDisabledState.BorderRadius = 18;
            this.btnDashboard.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnDashboard.OnDisabledState.BorderThickness = 1;
            this.btnDashboard.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnDashboard.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnDashboard.OnDisabledState.IconLeftImage = null;
            this.btnDashboard.OnDisabledState.IconRightImage = null;
            this.btnDashboard.onHoverState.BorderColor = System.Drawing.SystemColors.Control;
            this.btnDashboard.onHoverState.BorderRadius = 18;
            this.btnDashboard.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnDashboard.onHoverState.BorderThickness = 1;
            this.btnDashboard.onHoverState.FillColor = System.Drawing.Color.Gray;
            this.btnDashboard.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.btnDashboard.onHoverState.IconLeftImage = null;
            this.btnDashboard.onHoverState.IconRightImage = null;
            this.btnDashboard.OnIdleState.BorderColor = System.Drawing.SystemColors.Control;
            this.btnDashboard.OnIdleState.BorderRadius = 18;
            this.btnDashboard.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnDashboard.OnIdleState.BorderThickness = 1;
            this.btnDashboard.OnIdleState.FillColor = System.Drawing.SystemColors.Control;
            this.btnDashboard.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.btnDashboard.OnIdleState.IconLeftImage = null;
            this.btnDashboard.OnIdleState.IconRightImage = null;
            this.btnDashboard.OnPressedState.BorderColor = System.Drawing.SystemColors.Control;
            this.btnDashboard.OnPressedState.BorderRadius = 18;
            this.btnDashboard.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnDashboard.OnPressedState.BorderThickness = 1;
            this.btnDashboard.OnPressedState.FillColor = System.Drawing.Color.DarkBlue;
            this.btnDashboard.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnDashboard.OnPressedState.IconLeftImage = null;
            this.btnDashboard.OnPressedState.IconRightImage = null;
            this.btnDashboard.Size = new System.Drawing.Size(197, 39);
            this.btnDashboard.TabIndex = 14;
            this.btnDashboard.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnDashboard.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnDashboard.TextMarginLeft = 0;
            this.btnDashboard.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnDashboard.UseDefaultRadiusAndThickness = true;
            this.btnDashboard.Click += new System.EventHandler(this.btnDashboard_Click_1);
            // 
            // txtMindeus
            // 
            this.txtMindeus.AllowParentOverrides = false;
            this.txtMindeus.AutoEllipsis = false;
            this.txtMindeus.Cursor = System.Windows.Forms.Cursors.Default;
            this.txtMindeus.CursorType = System.Windows.Forms.Cursors.Default;
            this.txtMindeus.Font = new System.Drawing.Font("Gadugi", 26.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtMindeus.ForeColor = System.Drawing.Color.DarkBlue;
            this.txtMindeus.Location = new System.Drawing.Point(44, 41);
            this.txtMindeus.Name = "txtMindeus";
            this.txtMindeus.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.txtMindeus.Size = new System.Drawing.Size(163, 41);
            this.txtMindeus.TabIndex = 12;
            this.txtMindeus.Text = "MINDEUS";
            this.txtMindeus.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.txtMindeus.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // button2
            // 
            this.button2.AllowAnimations = true;
            this.button2.AllowMouseEffects = true;
            this.button2.AllowToggling = false;
            this.button2.AnimationSpeed = 200;
            this.button2.AutoGenerateColors = false;
            this.button2.AutoRoundBorders = false;
            this.button2.AutoSizeLeftIcon = true;
            this.button2.AutoSizeRightIcon = true;
            this.button2.BackColor = System.Drawing.Color.Transparent;
            this.button2.BackColor1 = System.Drawing.SystemColors.Control;
            this.button2.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("button2.BackgroundImage")));
            this.button2.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.button2.ButtonText = "Exit";
            this.button2.ButtonTextMarginLeft = 0;
            this.button2.ColorContrastOnClick = 45;
            this.button2.ColorContrastOnHover = 45;
            this.button2.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges11.BottomLeft = true;
            borderEdges11.BottomRight = true;
            borderEdges11.TopLeft = true;
            borderEdges11.TopRight = true;
            this.button2.CustomizableEdges = borderEdges11;
            this.button2.DialogResult = System.Windows.Forms.DialogResult.None;
            this.button2.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.button2.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.button2.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.button2.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.button2.Font = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.button2.ForeColor = System.Drawing.Color.Black;
            this.button2.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.button2.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.button2.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.button2.IconMarginLeft = 11;
            this.button2.IconPadding = 10;
            this.button2.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.button2.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.button2.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.button2.IconSize = 25;
            this.button2.IdleBorderColor = System.Drawing.SystemColors.Control;
            this.button2.IdleBorderRadius = 18;
            this.button2.IdleBorderThickness = 1;
            this.button2.IdleFillColor = System.Drawing.SystemColors.Control;
            this.button2.IdleIconLeftImage = null;
            this.button2.IdleIconRightImage = null;
            this.button2.IndicateFocus = false;
            this.button2.Location = new System.Drawing.Point(21, 753);
            this.button2.Name = "button2";
            this.button2.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.button2.OnDisabledState.BorderRadius = 18;
            this.button2.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.button2.OnDisabledState.BorderThickness = 1;
            this.button2.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.button2.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.button2.OnDisabledState.IconLeftImage = null;
            this.button2.OnDisabledState.IconRightImage = null;
            this.button2.onHoverState.BorderColor = System.Drawing.SystemColors.Control;
            this.button2.onHoverState.BorderRadius = 18;
            this.button2.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.button2.onHoverState.BorderThickness = 1;
            this.button2.onHoverState.FillColor = System.Drawing.Color.DarkBlue;
            this.button2.onHoverState.ForeColor = System.Drawing.Color.White;
            this.button2.onHoverState.IconLeftImage = null;
            this.button2.onHoverState.IconRightImage = null;
            this.button2.OnIdleState.BorderColor = System.Drawing.SystemColors.Control;
            this.button2.OnIdleState.BorderRadius = 18;
            this.button2.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.button2.OnIdleState.BorderThickness = 1;
            this.button2.OnIdleState.FillColor = System.Drawing.SystemColors.Control;
            this.button2.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.button2.OnIdleState.IconLeftImage = null;
            this.button2.OnIdleState.IconRightImage = null;
            this.button2.OnPressedState.BorderColor = System.Drawing.SystemColors.Control;
            this.button2.OnPressedState.BorderRadius = 18;
            this.button2.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.button2.OnPressedState.BorderThickness = 1;
            this.button2.OnPressedState.FillColor = System.Drawing.Color.DarkBlue;
            this.button2.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.button2.OnPressedState.IconLeftImage = null;
            this.button2.OnPressedState.IconRightImage = null;
            this.button2.Size = new System.Drawing.Size(197, 39);
            this.button2.TabIndex = 8;
            this.button2.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.button2.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.button2.TextMarginLeft = 0;
            this.button2.TextPadding = new System.Windows.Forms.Padding(0);
            this.button2.UseDefaultRadiusAndThickness = true;
            this.button2.Click += new System.EventHandler(this.button2_Click);
            // 
            // btnCustomer
            // 
            this.btnCustomer.AllowAnimations = true;
            this.btnCustomer.AllowMouseEffects = true;
            this.btnCustomer.AllowToggling = false;
            this.btnCustomer.AnimationSpeed = 200;
            this.btnCustomer.AutoGenerateColors = false;
            this.btnCustomer.AutoRoundBorders = false;
            this.btnCustomer.AutoSizeLeftIcon = true;
            this.btnCustomer.AutoSizeRightIcon = true;
            this.btnCustomer.BackColor = System.Drawing.Color.Transparent;
            this.btnCustomer.BackColor1 = System.Drawing.SystemColors.Control;
            this.btnCustomer.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnCustomer.BackgroundImage")));
            this.btnCustomer.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCustomer.ButtonText = "Customer";
            this.btnCustomer.ButtonTextMarginLeft = 0;
            this.btnCustomer.ColorContrastOnClick = 45;
            this.btnCustomer.ColorContrastOnHover = 45;
            this.btnCustomer.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges12.BottomLeft = true;
            borderEdges12.BottomRight = true;
            borderEdges12.TopLeft = true;
            borderEdges12.TopRight = true;
            this.btnCustomer.CustomizableEdges = borderEdges12;
            this.btnCustomer.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnCustomer.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnCustomer.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnCustomer.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnCustomer.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnCustomer.Font = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnCustomer.ForeColor = System.Drawing.Color.Black;
            this.btnCustomer.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnCustomer.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnCustomer.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnCustomer.IconMarginLeft = 11;
            this.btnCustomer.IconPadding = 10;
            this.btnCustomer.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnCustomer.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnCustomer.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnCustomer.IconSize = 25;
            this.btnCustomer.IdleBorderColor = System.Drawing.SystemColors.Control;
            this.btnCustomer.IdleBorderRadius = 18;
            this.btnCustomer.IdleBorderThickness = 1;
            this.btnCustomer.IdleFillColor = System.Drawing.SystemColors.Control;
            this.btnCustomer.IdleIconLeftImage = null;
            this.btnCustomer.IdleIconRightImage = null;
            this.btnCustomer.IndicateFocus = false;
            this.btnCustomer.Location = new System.Drawing.Point(21, 271);
            this.btnCustomer.Name = "btnCustomer";
            this.btnCustomer.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnCustomer.OnDisabledState.BorderRadius = 18;
            this.btnCustomer.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCustomer.OnDisabledState.BorderThickness = 1;
            this.btnCustomer.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnCustomer.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnCustomer.OnDisabledState.IconLeftImage = null;
            this.btnCustomer.OnDisabledState.IconRightImage = null;
            this.btnCustomer.onHoverState.BorderColor = System.Drawing.SystemColors.Control;
            this.btnCustomer.onHoverState.BorderRadius = 18;
            this.btnCustomer.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCustomer.onHoverState.BorderThickness = 1;
            this.btnCustomer.onHoverState.FillColor = System.Drawing.Color.Gray;
            this.btnCustomer.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.btnCustomer.onHoverState.IconLeftImage = null;
            this.btnCustomer.onHoverState.IconRightImage = null;
            this.btnCustomer.OnIdleState.BorderColor = System.Drawing.SystemColors.Control;
            this.btnCustomer.OnIdleState.BorderRadius = 18;
            this.btnCustomer.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCustomer.OnIdleState.BorderThickness = 1;
            this.btnCustomer.OnIdleState.FillColor = System.Drawing.SystemColors.Control;
            this.btnCustomer.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.btnCustomer.OnIdleState.IconLeftImage = null;
            this.btnCustomer.OnIdleState.IconRightImage = null;
            this.btnCustomer.OnPressedState.BorderColor = System.Drawing.SystemColors.Control;
            this.btnCustomer.OnPressedState.BorderRadius = 18;
            this.btnCustomer.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCustomer.OnPressedState.BorderThickness = 1;
            this.btnCustomer.OnPressedState.FillColor = System.Drawing.Color.DarkBlue;
            this.btnCustomer.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnCustomer.OnPressedState.IconLeftImage = null;
            this.btnCustomer.OnPressedState.IconRightImage = null;
            this.btnCustomer.Size = new System.Drawing.Size(197, 39);
            this.btnCustomer.TabIndex = 6;
            this.btnCustomer.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnCustomer.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnCustomer.TextMarginLeft = 0;
            this.btnCustomer.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnCustomer.UseDefaultRadiusAndThickness = true;
            this.btnCustomer.Click += new System.EventHandler(this.btnCustomer_Click_1);
            // 
            // btnOrder
            // 
            this.btnOrder.AllowAnimations = true;
            this.btnOrder.AllowMouseEffects = true;
            this.btnOrder.AllowToggling = false;
            this.btnOrder.AnimationSpeed = 200;
            this.btnOrder.AutoGenerateColors = false;
            this.btnOrder.AutoRoundBorders = false;
            this.btnOrder.AutoSizeLeftIcon = true;
            this.btnOrder.AutoSizeRightIcon = true;
            this.btnOrder.BackColor = System.Drawing.Color.Transparent;
            this.btnOrder.BackColor1 = System.Drawing.Color.DarkBlue;
            this.btnOrder.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnOrder.BackgroundImage")));
            this.btnOrder.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnOrder.ButtonText = "Orders";
            this.btnOrder.ButtonTextMarginLeft = 0;
            this.btnOrder.ColorContrastOnClick = 45;
            this.btnOrder.ColorContrastOnHover = 45;
            this.btnOrder.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges13.BottomLeft = true;
            borderEdges13.BottomRight = true;
            borderEdges13.TopLeft = true;
            borderEdges13.TopRight = true;
            this.btnOrder.CustomizableEdges = borderEdges13;
            this.btnOrder.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnOrder.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnOrder.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnOrder.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnOrder.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnOrder.Font = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnOrder.ForeColor = System.Drawing.Color.White;
            this.btnOrder.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnOrder.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnOrder.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnOrder.IconMarginLeft = 11;
            this.btnOrder.IconPadding = 10;
            this.btnOrder.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnOrder.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnOrder.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnOrder.IconSize = 25;
            this.btnOrder.IdleBorderColor = System.Drawing.SystemColors.Control;
            this.btnOrder.IdleBorderRadius = 18;
            this.btnOrder.IdleBorderThickness = 1;
            this.btnOrder.IdleFillColor = System.Drawing.Color.DarkBlue;
            this.btnOrder.IdleIconLeftImage = null;
            this.btnOrder.IdleIconRightImage = null;
            this.btnOrder.IndicateFocus = false;
            this.btnOrder.Location = new System.Drawing.Point(21, 214);
            this.btnOrder.Name = "btnOrder";
            this.btnOrder.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnOrder.OnDisabledState.BorderRadius = 18;
            this.btnOrder.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnOrder.OnDisabledState.BorderThickness = 1;
            this.btnOrder.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnOrder.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnOrder.OnDisabledState.IconLeftImage = null;
            this.btnOrder.OnDisabledState.IconRightImage = null;
            this.btnOrder.onHoverState.BorderColor = System.Drawing.SystemColors.Control;
            this.btnOrder.onHoverState.BorderRadius = 18;
            this.btnOrder.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnOrder.onHoverState.BorderThickness = 1;
            this.btnOrder.onHoverState.FillColor = System.Drawing.Color.DarkBlue;
            this.btnOrder.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnOrder.onHoverState.IconLeftImage = null;
            this.btnOrder.onHoverState.IconRightImage = null;
            this.btnOrder.OnIdleState.BorderColor = System.Drawing.SystemColors.Control;
            this.btnOrder.OnIdleState.BorderRadius = 18;
            this.btnOrder.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnOrder.OnIdleState.BorderThickness = 1;
            this.btnOrder.OnIdleState.FillColor = System.Drawing.Color.DarkBlue;
            this.btnOrder.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnOrder.OnIdleState.IconLeftImage = null;
            this.btnOrder.OnIdleState.IconRightImage = null;
            this.btnOrder.OnPressedState.BorderColor = System.Drawing.SystemColors.Control;
            this.btnOrder.OnPressedState.BorderRadius = 18;
            this.btnOrder.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnOrder.OnPressedState.BorderThickness = 1;
            this.btnOrder.OnPressedState.FillColor = System.Drawing.Color.DarkBlue;
            this.btnOrder.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnOrder.OnPressedState.IconLeftImage = null;
            this.btnOrder.OnPressedState.IconRightImage = null;
            this.btnOrder.Size = new System.Drawing.Size(197, 39);
            this.btnOrder.TabIndex = 5;
            this.btnOrder.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnOrder.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnOrder.TextMarginLeft = 0;
            this.btnOrder.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnOrder.UseDefaultRadiusAndThickness = true;
            // 
            // bunifuPictureBox1
            // 
            this.bunifuPictureBox1.AllowFocused = false;
            this.bunifuPictureBox1.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.bunifuPictureBox1.AutoSizeHeight = false;
            this.bunifuPictureBox1.BorderRadius = 0;
            this.bunifuPictureBox1.Image = global::barcodescanner.Properties.Resources.linya;
            this.bunifuPictureBox1.IsCircle = true;
            this.bunifuPictureBox1.Location = new System.Drawing.Point(44, 664);
            this.bunifuPictureBox1.Name = "bunifuPictureBox1";
            this.bunifuPictureBox1.Size = new System.Drawing.Size(150, 150);
            this.bunifuPictureBox1.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.bunifuPictureBox1.TabIndex = 4;
            this.bunifuPictureBox1.TabStop = false;
            this.bunifuPictureBox1.Type = Bunifu.UI.WinForms.BunifuPictureBox.Types.Square;
            // 
            // btnPrint
            // 
            this.btnPrint.AllowAnimations = true;
            this.btnPrint.AllowMouseEffects = true;
            this.btnPrint.AllowToggling = false;
            this.btnPrint.AnimationSpeed = 200;
            this.btnPrint.AutoGenerateColors = false;
            this.btnPrint.AutoRoundBorders = false;
            this.btnPrint.AutoSizeLeftIcon = true;
            this.btnPrint.AutoSizeRightIcon = true;
            this.btnPrint.BackColor = System.Drawing.Color.Transparent;
            this.btnPrint.BackColor1 = System.Drawing.SystemColors.Control;
            this.btnPrint.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnPrint.BackgroundImage")));
            this.btnPrint.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnPrint.ButtonText = "Export";
            this.btnPrint.ButtonTextMarginLeft = 0;
            this.btnPrint.ColorContrastOnClick = 45;
            this.btnPrint.ColorContrastOnHover = 45;
            this.btnPrint.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges14.BottomLeft = true;
            borderEdges14.BottomRight = true;
            borderEdges14.TopLeft = true;
            borderEdges14.TopRight = true;
            this.btnPrint.CustomizableEdges = borderEdges14;
            this.btnPrint.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnPrint.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnPrint.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnPrint.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnPrint.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnPrint.Font = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnPrint.ForeColor = System.Drawing.Color.Black;
            this.btnPrint.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnPrint.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnPrint.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnPrint.IconMarginLeft = 11;
            this.btnPrint.IconPadding = 10;
            this.btnPrint.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnPrint.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnPrint.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnPrint.IconSize = 25;
            this.btnPrint.IdleBorderColor = System.Drawing.Color.Black;
            this.btnPrint.IdleBorderRadius = 18;
            this.btnPrint.IdleBorderThickness = 1;
            this.btnPrint.IdleFillColor = System.Drawing.SystemColors.Control;
            this.btnPrint.IdleIconLeftImage = null;
            this.btnPrint.IdleIconRightImage = null;
            this.btnPrint.IndicateFocus = false;
            this.btnPrint.Location = new System.Drawing.Point(974, 737);
            this.btnPrint.Name = "btnPrint";
            this.btnPrint.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnPrint.OnDisabledState.BorderRadius = 18;
            this.btnPrint.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnPrint.OnDisabledState.BorderThickness = 1;
            this.btnPrint.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnPrint.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnPrint.OnDisabledState.IconLeftImage = null;
            this.btnPrint.OnDisabledState.IconRightImage = null;
            this.btnPrint.onHoverState.BorderColor = System.Drawing.SystemColors.Control;
            this.btnPrint.onHoverState.BorderRadius = 18;
            this.btnPrint.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnPrint.onHoverState.BorderThickness = 1;
            this.btnPrint.onHoverState.FillColor = System.Drawing.Color.DarkBlue;
            this.btnPrint.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnPrint.onHoverState.IconLeftImage = null;
            this.btnPrint.onHoverState.IconRightImage = null;
            this.btnPrint.OnIdleState.BorderColor = System.Drawing.Color.Black;
            this.btnPrint.OnIdleState.BorderRadius = 18;
            this.btnPrint.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnPrint.OnIdleState.BorderThickness = 1;
            this.btnPrint.OnIdleState.FillColor = System.Drawing.SystemColors.Control;
            this.btnPrint.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.btnPrint.OnIdleState.IconLeftImage = null;
            this.btnPrint.OnIdleState.IconRightImage = null;
            this.btnPrint.OnPressedState.BorderColor = System.Drawing.SystemColors.Control;
            this.btnPrint.OnPressedState.BorderRadius = 18;
            this.btnPrint.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnPrint.OnPressedState.BorderThickness = 1;
            this.btnPrint.OnPressedState.FillColor = System.Drawing.Color.DarkBlue;
            this.btnPrint.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnPrint.OnPressedState.IconLeftImage = null;
            this.btnPrint.OnPressedState.IconRightImage = null;
            this.btnPrint.Size = new System.Drawing.Size(197, 39);
            this.btnPrint.TabIndex = 48;
            this.btnPrint.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnPrint.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnPrint.TextMarginLeft = 0;
            this.btnPrint.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnPrint.UseDefaultRadiusAndThickness = true;
            this.btnPrint.Click += new System.EventHandler(this.btnPrint_Click);
            // 
            // Items
            // 
            this.Items.AllowCustomTheming = true;
            this.Items.AllowUserToAddRows = false;
            this.Items.AllowUserToDeleteRows = false;
            this.Items.AllowUserToResizeColumns = false;
            this.Items.AllowUserToResizeRows = false;
            dataGridViewCellStyle4.BackColor = System.Drawing.SystemColors.Control;
            dataGridViewCellStyle4.ForeColor = System.Drawing.Color.Black;
            this.Items.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle4;
            this.Items.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.Items.BackgroundColor = System.Drawing.SystemColors.Control;
            this.Items.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.Items.CellBorderStyle = System.Windows.Forms.DataGridViewCellBorderStyle.SingleHorizontal;
            this.Items.ColumnHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
            dataGridViewCellStyle5.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle5.BackColor = System.Drawing.Color.DarkBlue;
            dataGridViewCellStyle5.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle5.ForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle5.SelectionBackColor = System.Drawing.Color.DarkBlue;
            dataGridViewCellStyle5.SelectionForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle5.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.Items.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle5;
            this.Items.ColumnHeadersHeight = 40;
            this.Items.CurrentTheme.AlternatingRowsStyle.BackColor = System.Drawing.SystemColors.Control;
            this.Items.CurrentTheme.AlternatingRowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.Items.CurrentTheme.AlternatingRowsStyle.ForeColor = System.Drawing.Color.Black;
            this.Items.CurrentTheme.AlternatingRowsStyle.SelectionBackColor = System.Drawing.Color.DarkBlue;
            this.Items.CurrentTheme.AlternatingRowsStyle.SelectionForeColor = System.Drawing.Color.White;
            this.Items.CurrentTheme.BackColor = System.Drawing.SystemColors.Control;
            this.Items.CurrentTheme.GridColor = System.Drawing.Color.Black;
            this.Items.CurrentTheme.HeaderStyle.BackColor = System.Drawing.Color.DarkBlue;
            this.Items.CurrentTheme.HeaderStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            this.Items.CurrentTheme.HeaderStyle.ForeColor = System.Drawing.Color.White;
            this.Items.CurrentTheme.HeaderStyle.SelectionBackColor = System.Drawing.Color.DarkBlue;
            this.Items.CurrentTheme.HeaderStyle.SelectionForeColor = System.Drawing.Color.White;
            this.Items.CurrentTheme.Name = null;
            this.Items.CurrentTheme.RowsStyle.BackColor = System.Drawing.SystemColors.Control;
            this.Items.CurrentTheme.RowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.Items.CurrentTheme.RowsStyle.ForeColor = System.Drawing.Color.Black;
            this.Items.CurrentTheme.RowsStyle.SelectionBackColor = System.Drawing.Color.DarkBlue;
            this.Items.CurrentTheme.RowsStyle.SelectionForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle6.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle6.BackColor = System.Drawing.SystemColors.Control;
            dataGridViewCellStyle6.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle6.ForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle6.SelectionBackColor = System.Drawing.Color.DarkBlue;
            dataGridViewCellStyle6.SelectionForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle6.WrapMode = System.Windows.Forms.DataGridViewTriState.False;
            this.Items.DefaultCellStyle = dataGridViewCellStyle6;
            this.Items.EnableHeadersVisualStyles = false;
            this.Items.GridColor = System.Drawing.Color.Black;
            this.Items.HeaderBackColor = System.Drawing.Color.DarkBlue;
            this.Items.HeaderBgColor = System.Drawing.Color.Empty;
            this.Items.HeaderForeColor = System.Drawing.Color.White;
            this.Items.Location = new System.Drawing.Point(966, 80);
            this.Items.Name = "Items";
            this.Items.ReadOnly = true;
            this.Items.RowHeadersVisible = false;
            this.Items.RowTemplate.Height = 40;
            this.Items.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.Items.Size = new System.Drawing.Size(408, 620);
            this.Items.TabIndex = 55;
            this.Items.Theme = Bunifu.UI.WinForms.BunifuDataGridView.PresetThemes.Light;
            this.Items.CellClick += new System.Windows.Forms.DataGridViewCellEventHandler(this.Items_CellClick);
            this.Items.CellContentClick += new System.Windows.Forms.DataGridViewCellEventHandler(this.Items_CellContentClick);
            this.Items.CellEndEdit += new System.Windows.Forms.DataGridViewCellEventHandler(this.Items_CellEndEdit);
            // 
            // cboCategory
            // 
            this.cboCategory.BackColor = System.Drawing.Color.Transparent;
            this.cboCategory.BackgroundColor = System.Drawing.Color.White;
            this.cboCategory.BorderColor = System.Drawing.Color.Silver;
            this.cboCategory.BorderRadius = 17;
            this.cboCategory.Color = System.Drawing.Color.Silver;
            this.cboCategory.Direction = Bunifu.UI.WinForms.BunifuDropdown.Directions.Down;
            this.cboCategory.DisabledBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.cboCategory.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.cboCategory.DisabledColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.cboCategory.DisabledForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            this.cboCategory.DisabledIndicatorColor = System.Drawing.Color.DarkGray;
            this.cboCategory.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
            this.cboCategory.DropdownBorderThickness = Bunifu.UI.WinForms.BunifuDropdown.BorderThickness.Thin;
            this.cboCategory.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cboCategory.DropDownTextAlign = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.cboCategory.FillDropDown = true;
            this.cboCategory.FillIndicator = false;
            this.cboCategory.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.cboCategory.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.cboCategory.ForeColor = System.Drawing.Color.Black;
            this.cboCategory.FormattingEnabled = true;
            this.cboCategory.Icon = null;
            this.cboCategory.IndicatorAlignment = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.cboCategory.IndicatorColor = System.Drawing.Color.Gray;
            this.cboCategory.IndicatorLocation = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.cboCategory.ItemBackColor = System.Drawing.Color.White;
            this.cboCategory.ItemBorderColor = System.Drawing.Color.White;
            this.cboCategory.ItemForeColor = System.Drawing.Color.Black;
            this.cboCategory.ItemHeight = 26;
            this.cboCategory.ItemHighLightColor = System.Drawing.Color.DodgerBlue;
            this.cboCategory.ItemHighLightForeColor = System.Drawing.Color.White;
            this.cboCategory.ItemTopMargin = 3;
            this.cboCategory.Location = new System.Drawing.Point(716, 28);
            this.cboCategory.Name = "cboCategory";
            this.cboCategory.Size = new System.Drawing.Size(232, 32);
            this.cboCategory.TabIndex = 51;
            this.cboCategory.Text = null;
            this.cboCategory.TextAlignment = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.cboCategory.TextLeftMargin = 5;
            this.cboCategory.SelectedIndexChanged += new System.EventHandler(this.cboCategory_SelectedIndexChanged);
            // 
            // flowLayoutPanel1
            // 
            this.flowLayoutPanel1.Location = new System.Drawing.Point(193, 3);
            this.flowLayoutPanel1.Name = "flowLayoutPanel1";
            this.flowLayoutPanel1.Size = new System.Drawing.Size(200, 100);
            this.flowLayoutPanel1.TabIndex = 1;
            // 
            // txtProductName
            // 
            this.txtProductName.AllowParentOverrides = false;
            this.txtProductName.AutoEllipsis = false;
            this.txtProductName.Cursor = System.Windows.Forms.Cursors.Default;
            this.txtProductName.CursorType = System.Windows.Forms.Cursors.Default;
            this.txtProductName.Font = new System.Drawing.Font("Tahoma", 15.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtProductName.Location = new System.Drawing.Point(17, 125);
            this.txtProductName.Name = "txtProductName";
            this.txtProductName.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.txtProductName.Size = new System.Drawing.Size(149, 25);
            this.txtProductName.TabIndex = 1;
            this.txtProductName.Text = "Product Name";
            this.txtProductName.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.txtProductName.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuButton1
            // 
            this.bunifuButton1.AllowAnimations = true;
            this.bunifuButton1.AllowMouseEffects = true;
            this.bunifuButton1.AllowToggling = false;
            this.bunifuButton1.AnimationSpeed = 200;
            this.bunifuButton1.AutoGenerateColors = false;
            this.bunifuButton1.AutoRoundBorders = false;
            this.bunifuButton1.AutoSizeLeftIcon = true;
            this.bunifuButton1.AutoSizeRightIcon = true;
            this.bunifuButton1.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButton1.BackColor1 = System.Drawing.SystemColors.Control;
            this.bunifuButton1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton1.BackgroundImage")));
            this.bunifuButton1.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.ButtonText = "Go Back";
            this.bunifuButton1.ButtonTextMarginLeft = 0;
            this.bunifuButton1.ColorContrastOnClick = 45;
            this.bunifuButton1.ColorContrastOnHover = 45;
            this.bunifuButton1.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges15.BottomLeft = true;
            borderEdges15.BottomRight = true;
            borderEdges15.TopLeft = true;
            borderEdges15.TopRight = true;
            this.bunifuButton1.CustomizableEdges = borderEdges15;
            this.bunifuButton1.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButton1.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton1.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton1.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton1.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.bunifuButton1.Font = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Bold);
            this.bunifuButton1.ForeColor = System.Drawing.Color.Black;
            this.bunifuButton1.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButton1.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton1.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bunifuButton1.IconMarginLeft = 11;
            this.bunifuButton1.IconPadding = 10;
            this.bunifuButton1.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButton1.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton1.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bunifuButton1.IconSize = 25;
            this.bunifuButton1.IdleBorderColor = System.Drawing.Color.Black;
            this.bunifuButton1.IdleBorderRadius = 20;
            this.bunifuButton1.IdleBorderThickness = 1;
            this.bunifuButton1.IdleFillColor = System.Drawing.SystemColors.Control;
            this.bunifuButton1.IdleIconLeftImage = null;
            this.bunifuButton1.IdleIconRightImage = null;
            this.bunifuButton1.IndicateFocus = false;
            this.bunifuButton1.Location = new System.Drawing.Point(1435, 28);
            this.bunifuButton1.Name = "bunifuButton1";
            this.bunifuButton1.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton1.OnDisabledState.BorderRadius = 20;
            this.bunifuButton1.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.OnDisabledState.BorderThickness = 1;
            this.bunifuButton1.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton1.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton1.OnDisabledState.IconLeftImage = null;
            this.bunifuButton1.OnDisabledState.IconRightImage = null;
            this.bunifuButton1.onHoverState.BorderColor = System.Drawing.SystemColors.Control;
            this.bunifuButton1.onHoverState.BorderRadius = 20;
            this.bunifuButton1.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.onHoverState.BorderThickness = 1;
            this.bunifuButton1.onHoverState.FillColor = System.Drawing.Color.DarkBlue;
            this.bunifuButton1.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton1.onHoverState.IconLeftImage = null;
            this.bunifuButton1.onHoverState.IconRightImage = null;
            this.bunifuButton1.OnIdleState.BorderColor = System.Drawing.Color.Black;
            this.bunifuButton1.OnIdleState.BorderRadius = 20;
            this.bunifuButton1.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.OnIdleState.BorderThickness = 1;
            this.bunifuButton1.OnIdleState.FillColor = System.Drawing.SystemColors.Control;
            this.bunifuButton1.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.bunifuButton1.OnIdleState.IconLeftImage = null;
            this.bunifuButton1.OnIdleState.IconRightImage = null;
            this.bunifuButton1.OnPressedState.BorderColor = System.Drawing.SystemColors.Control;
            this.bunifuButton1.OnPressedState.BorderRadius = 20;
            this.bunifuButton1.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.OnPressedState.BorderThickness = 1;
            this.bunifuButton1.OnPressedState.FillColor = System.Drawing.Color.DarkBlue;
            this.bunifuButton1.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton1.OnPressedState.IconLeftImage = null;
            this.bunifuButton1.OnPressedState.IconRightImage = null;
            this.bunifuButton1.Size = new System.Drawing.Size(103, 32);
            this.bunifuButton1.TabIndex = 57;
            this.bunifuButton1.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuButton1.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButton1.TextMarginLeft = 0;
            this.bunifuButton1.TextPadding = new System.Windows.Forms.Padding(0);
            this.bunifuButton1.UseDefaultRadiusAndThickness = true;
            // 
            // panel
            // 
            this.panel.AutoScroll = true;
            this.panel.Controls.Add(this.bunifuShadowPanel1);
            this.panel.Controls.Add(this.flowLayoutPanel1);
            this.panel.Location = new System.Drawing.Point(260, 77);
            this.panel.Name = "panel";
            this.panel.Size = new System.Drawing.Size(688, 623);
            this.panel.TabIndex = 56;
            // 
            // bunifuShadowPanel1
            // 
            this.bunifuShadowPanel1.BackColor = System.Drawing.Color.Transparent;
            this.bunifuShadowPanel1.BorderColor = System.Drawing.Color.WhiteSmoke;
            this.bunifuShadowPanel1.BorderRadius = 15;
            this.bunifuShadowPanel1.BorderThickness = 1;
            this.bunifuShadowPanel1.Controls.Add(this.picture);
            this.bunifuShadowPanel1.Controls.Add(this.txtPrice);
            this.bunifuShadowPanel1.Controls.Add(this.txtProductName);
            this.bunifuShadowPanel1.FillStyle = Bunifu.UI.WinForms.BunifuShadowPanel.FillStyles.Solid;
            this.bunifuShadowPanel1.GradientMode = Bunifu.UI.WinForms.BunifuShadowPanel.GradientModes.Horizontal;
            this.bunifuShadowPanel1.Location = new System.Drawing.Point(3, 3);
            this.bunifuShadowPanel1.Name = "bunifuShadowPanel1";
            this.bunifuShadowPanel1.PanelColor = System.Drawing.Color.WhiteSmoke;
            this.bunifuShadowPanel1.PanelColor2 = System.Drawing.Color.WhiteSmoke;
            this.bunifuShadowPanel1.ShadowColor = System.Drawing.Color.DarkGray;
            this.bunifuShadowPanel1.ShadowDept = 2;
            this.bunifuShadowPanel1.ShadowDepth = 5;
            this.bunifuShadowPanel1.ShadowStyle = Bunifu.UI.WinForms.BunifuShadowPanel.ShadowStyles.Surrounded;
            this.bunifuShadowPanel1.ShadowTopLeftVisible = false;
            this.bunifuShadowPanel1.Size = new System.Drawing.Size(184, 202);
            this.bunifuShadowPanel1.Style = Bunifu.UI.WinForms.BunifuShadowPanel.BevelStyles.Flat;
            this.bunifuShadowPanel1.TabIndex = 0;
            // 
            // picture
            // 
            this.picture.AllowFocused = false;
            this.picture.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.picture.AutoSizeHeight = true;
            this.picture.BorderRadius = 0;
            this.picture.Image = ((System.Drawing.Image)(resources.GetObject("picture.Image")));
            this.picture.IsCircle = true;
            this.picture.Location = new System.Drawing.Point(32, 0);
            this.picture.Name = "picture";
            this.picture.Size = new System.Drawing.Size(109, 109);
            this.picture.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.picture.TabIndex = 0;
            this.picture.TabStop = false;
            this.picture.Type = Bunifu.UI.WinForms.BunifuPictureBox.Types.Square;
            // 
            // txtPrice
            // 
            this.txtPrice.AllowParentOverrides = false;
            this.txtPrice.AutoEllipsis = false;
            this.txtPrice.CursorType = null;
            this.txtPrice.Font = new System.Drawing.Font("Tahoma", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtPrice.Location = new System.Drawing.Point(70, 156);
            this.txtPrice.Name = "txtPrice";
            this.txtPrice.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.txtPrice.Size = new System.Drawing.Size(35, 19);
            this.txtPrice.TabIndex = 2;
            this.txtPrice.Text = "0.00";
            this.txtPrice.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.txtPrice.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // btnClear
            // 
            this.btnClear.AllowAnimations = true;
            this.btnClear.AllowMouseEffects = true;
            this.btnClear.AllowToggling = false;
            this.btnClear.AnimationSpeed = 200;
            this.btnClear.AutoGenerateColors = false;
            this.btnClear.AutoRoundBorders = false;
            this.btnClear.AutoSizeLeftIcon = true;
            this.btnClear.AutoSizeRightIcon = true;
            this.btnClear.BackColor = System.Drawing.Color.Transparent;
            this.btnClear.BackColor1 = System.Drawing.SystemColors.Control;
            this.btnClear.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnClear.BackgroundImage")));
            this.btnClear.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnClear.ButtonText = "Clear";
            this.btnClear.ButtonTextMarginLeft = 0;
            this.btnClear.ColorContrastOnClick = 45;
            this.btnClear.ColorContrastOnHover = 45;
            this.btnClear.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges16.BottomLeft = true;
            borderEdges16.BottomRight = true;
            borderEdges16.TopLeft = true;
            borderEdges16.TopRight = true;
            this.btnClear.CustomizableEdges = borderEdges16;
            this.btnClear.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnClear.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnClear.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnClear.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnClear.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnClear.Font = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Bold);
            this.btnClear.ForeColor = System.Drawing.Color.Black;
            this.btnClear.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnClear.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnClear.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnClear.IconMarginLeft = 11;
            this.btnClear.IconPadding = 10;
            this.btnClear.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnClear.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnClear.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnClear.IconSize = 25;
            this.btnClear.IdleBorderColor = System.Drawing.Color.Black;
            this.btnClear.IdleBorderRadius = 20;
            this.btnClear.IdleBorderThickness = 1;
            this.btnClear.IdleFillColor = System.Drawing.SystemColors.Control;
            this.btnClear.IdleIconLeftImage = null;
            this.btnClear.IdleIconRightImage = null;
            this.btnClear.IndicateFocus = false;
            this.btnClear.Location = new System.Drawing.Point(1177, 737);
            this.btnClear.Name = "btnClear";
            this.btnClear.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnClear.OnDisabledState.BorderRadius = 20;
            this.btnClear.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnClear.OnDisabledState.BorderThickness = 1;
            this.btnClear.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnClear.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnClear.OnDisabledState.IconLeftImage = null;
            this.btnClear.OnDisabledState.IconRightImage = null;
            this.btnClear.onHoverState.BorderColor = System.Drawing.SystemColors.Control;
            this.btnClear.onHoverState.BorderRadius = 20;
            this.btnClear.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnClear.onHoverState.BorderThickness = 1;
            this.btnClear.onHoverState.FillColor = System.Drawing.Color.DarkBlue;
            this.btnClear.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnClear.onHoverState.IconLeftImage = null;
            this.btnClear.onHoverState.IconRightImage = null;
            this.btnClear.OnIdleState.BorderColor = System.Drawing.Color.Black;
            this.btnClear.OnIdleState.BorderRadius = 20;
            this.btnClear.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnClear.OnIdleState.BorderThickness = 1;
            this.btnClear.OnIdleState.FillColor = System.Drawing.SystemColors.Control;
            this.btnClear.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.btnClear.OnIdleState.IconLeftImage = null;
            this.btnClear.OnIdleState.IconRightImage = null;
            this.btnClear.OnPressedState.BorderColor = System.Drawing.SystemColors.Control;
            this.btnClear.OnPressedState.BorderRadius = 20;
            this.btnClear.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnClear.OnPressedState.BorderThickness = 1;
            this.btnClear.OnPressedState.FillColor = System.Drawing.Color.DarkBlue;
            this.btnClear.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnClear.OnPressedState.IconLeftImage = null;
            this.btnClear.OnPressedState.IconRightImage = null;
            this.btnClear.Size = new System.Drawing.Size(206, 39);
            this.btnClear.TabIndex = 53;
            this.btnClear.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnClear.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnClear.TextMarginLeft = 0;
            this.btnClear.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnClear.UseDefaultRadiusAndThickness = true;
            this.btnClear.Click += new System.EventHandler(this.btnClear_Click);
            // 
            // cboCustomer
            // 
            this.cboCustomer.BackColor = System.Drawing.Color.Transparent;
            this.cboCustomer.BackgroundColor = System.Drawing.Color.White;
            this.cboCustomer.BorderColor = System.Drawing.Color.Silver;
            this.cboCustomer.BorderRadius = 17;
            this.cboCustomer.Color = System.Drawing.Color.Silver;
            this.cboCustomer.Direction = Bunifu.UI.WinForms.BunifuDropdown.Directions.Down;
            this.cboCustomer.DisabledBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.cboCustomer.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.cboCustomer.DisabledColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.cboCustomer.DisabledForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            this.cboCustomer.DisabledIndicatorColor = System.Drawing.Color.DarkGray;
            this.cboCustomer.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
            this.cboCustomer.DropdownBorderThickness = Bunifu.UI.WinForms.BunifuDropdown.BorderThickness.Thin;
            this.cboCustomer.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cboCustomer.DropDownTextAlign = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.cboCustomer.FillDropDown = true;
            this.cboCustomer.FillIndicator = false;
            this.cboCustomer.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.cboCustomer.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.cboCustomer.ForeColor = System.Drawing.Color.Black;
            this.cboCustomer.FormattingEnabled = true;
            this.cboCustomer.Icon = null;
            this.cboCustomer.IndicatorAlignment = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.cboCustomer.IndicatorColor = System.Drawing.Color.Gray;
            this.cboCustomer.IndicatorLocation = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.cboCustomer.ItemBackColor = System.Drawing.Color.White;
            this.cboCustomer.ItemBorderColor = System.Drawing.Color.White;
            this.cboCustomer.ItemForeColor = System.Drawing.Color.Black;
            this.cboCustomer.ItemHeight = 26;
            this.cboCustomer.ItemHighLightColor = System.Drawing.Color.DodgerBlue;
            this.cboCustomer.ItemHighLightForeColor = System.Drawing.Color.White;
            this.cboCustomer.ItemTopMargin = 3;
            this.cboCustomer.Location = new System.Drawing.Point(493, 28);
            this.cboCustomer.Name = "cboCustomer";
            this.cboCustomer.Size = new System.Drawing.Size(217, 32);
            this.cboCustomer.TabIndex = 50;
            this.cboCustomer.Text = null;
            this.cboCustomer.TextAlignment = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.cboCustomer.TextLeftMargin = 5;
            this.cboCustomer.SelectedIndexChanged += new System.EventHandler(this.cboCustomer_SelectedIndexChanged);
            // 
            // bunifuDatePicker1
            // 
            this.bunifuDatePicker1.BackColor = System.Drawing.Color.Transparent;
            this.bunifuDatePicker1.BorderRadius = 17;
            this.bunifuDatePicker1.Color = System.Drawing.Color.Silver;
            this.bunifuDatePicker1.DateBorderThickness = Bunifu.UI.WinForms.BunifuDatePicker.BorderThickness.Thin;
            this.bunifuDatePicker1.DateTextAlign = Bunifu.UI.WinForms.BunifuDatePicker.TextAlign.Left;
            this.bunifuDatePicker1.DisabledColor = System.Drawing.Color.Gray;
            this.bunifuDatePicker1.DisplayWeekNumbers = false;
            this.bunifuDatePicker1.DPHeight = 0;
            this.bunifuDatePicker1.DropDownAlign = System.Windows.Forms.LeftRightAlignment.Right;
            this.bunifuDatePicker1.FillDatePicker = false;
            this.bunifuDatePicker1.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuDatePicker1.ForeColor = System.Drawing.Color.Black;
            this.bunifuDatePicker1.Icon = ((System.Drawing.Image)(resources.GetObject("bunifuDatePicker1.Icon")));
            this.bunifuDatePicker1.IconColor = System.Drawing.Color.Gray;
            this.bunifuDatePicker1.IconLocation = Bunifu.UI.WinForms.BunifuDatePicker.Indicator.Right;
            this.bunifuDatePicker1.LeftTextMargin = 5;
            this.bunifuDatePicker1.Location = new System.Drawing.Point(263, 28);
            this.bunifuDatePicker1.MinimumSize = new System.Drawing.Size(4, 32);
            this.bunifuDatePicker1.Name = "bunifuDatePicker1";
            this.bunifuDatePicker1.Size = new System.Drawing.Size(224, 32);
            this.bunifuDatePicker1.TabIndex = 49;
            // 
            // bunifuPanel2
            // 
            this.bunifuPanel2.BackgroundColor = System.Drawing.Color.DarkBlue;
            this.bunifuPanel2.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuPanel2.BackgroundImage")));
            this.bunifuPanel2.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuPanel2.BorderColor = System.Drawing.Color.Transparent;
            this.bunifuPanel2.BorderRadius = 5;
            this.bunifuPanel2.BorderThickness = 1;
            this.bunifuPanel2.Controls.Add(this.txtTotal);
            this.bunifuPanel2.Controls.Add(this.bunifuLabel1);
            this.bunifuPanel2.Font = new System.Drawing.Font("Segoe UI", 14.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuPanel2.Location = new System.Drawing.Point(966, 12);
            this.bunifuPanel2.Name = "bunifuPanel2";
            this.bunifuPanel2.ShowBorders = true;
            this.bunifuPanel2.Size = new System.Drawing.Size(417, 62);
            this.bunifuPanel2.TabIndex = 59;
            // 
            // txtTotal
            // 
            this.txtTotal.AllowParentOverrides = false;
            this.txtTotal.AutoEllipsis = false;
            this.txtTotal.CursorType = null;
            this.txtTotal.Font = new System.Drawing.Font("Segoe UI", 24F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtTotal.ForeColor = System.Drawing.Color.Transparent;
            this.txtTotal.Location = new System.Drawing.Point(255, 4);
            this.txtTotal.Name = "txtTotal";
            this.txtTotal.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.txtTotal.Size = new System.Drawing.Size(63, 45);
            this.txtTotal.TabIndex = 1;
            this.txtTotal.Text = "0.00";
            this.txtTotal.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.txtTotal.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel1
            // 
            this.bunifuLabel1.AllowParentOverrides = false;
            this.bunifuLabel1.AutoEllipsis = false;
            this.bunifuLabel1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.None;
            this.bunifuLabel1.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.Font = new System.Drawing.Font("Segoe UI", 20.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel1.ForeColor = System.Drawing.Color.Transparent;
            this.bunifuLabel1.Location = new System.Drawing.Point(26, 9);
            this.bunifuLabel1.Name = "bunifuLabel1";
            this.bunifuLabel1.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel1.Size = new System.Drawing.Size(166, 37);
            this.bunifuLabel1.TabIndex = 0;
            this.bunifuLabel1.Text = "Grand Total :";
            this.bunifuLabel1.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel1.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuElipse1
            // 
            this.bunifuElipse1.ElipseRadius = 50;
            this.bunifuElipse1.TargetControl = this;
            // 
            // Order
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(1384, 814);
            this.ControlBox = false;
            this.Controls.Add(this.bunifuPanel2);
            this.Controls.Add(this.cboCategory);
            this.Controls.Add(this.bunifuButton1);
            this.Controls.Add(this.panel);
            this.Controls.Add(this.btnClear);
            this.Controls.Add(this.cboCustomer);
            this.Controls.Add(this.bunifuDatePicker1);
            this.Controls.Add(this.btnPrint);
            this.Controls.Add(this.bunifuPanel1);
            this.Controls.Add(this.Items);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Icon = ((System.Drawing.Icon)(resources.GetObject("$this.Icon")));
            this.Name = "Order";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Order";
            this.Load += new System.EventHandler(this.Order_Load);
            this.bunifuPanel1.ResumeLayout(false);
            this.bunifuPanel1.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.bunifuPictureBox1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.Items)).EndInit();
            this.panel.ResumeLayout(false);
            this.bunifuShadowPanel1.ResumeLayout(false);
            this.bunifuShadowPanel1.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.picture)).EndInit();
            this.bunifuPanel2.ResumeLayout(false);
            this.bunifuPanel2.PerformLayout();
            this.ResumeLayout(false);

        }

        #endregion
        private Bunifu.UI.WinForms.BunifuPanel bunifuPanel1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnDashboard;
        private Bunifu.UI.WinForms.BunifuLabel txtMindeus;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton button2;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnCustomer;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnOrder;
        private Bunifu.UI.WinForms.BunifuPictureBox bunifuPictureBox1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnHistory;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnPrint;
        private Bunifu.UI.WinForms.BunifuDataGridView Items;
        private Bunifu.UI.WinForms.BunifuDropdown cboCategory;
        private System.Windows.Forms.FlowLayoutPanel flowLayoutPanel1;
        private Bunifu.UI.WinForms.BunifuLabel txtProductName;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton bunifuButton1;
        private System.Windows.Forms.FlowLayoutPanel panel;
        private Bunifu.UI.WinForms.BunifuShadowPanel bunifuShadowPanel1;
        private Bunifu.UI.WinForms.BunifuPictureBox picture;
        private Bunifu.UI.WinForms.BunifuLabel txtPrice;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnClear;
        private Bunifu.UI.WinForms.BunifuDropdown cboCustomer;
        private Bunifu.UI.WinForms.BunifuDatePicker bunifuDatePicker1;
        private Bunifu.UI.WinForms.BunifuPanel bunifuPanel2;
        private Bunifu.UI.WinForms.BunifuLabel txtTotal;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel1;
        private Bunifu.Framework.UI.BunifuElipse bunifuElipse1;
    }
}